//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-04-22T22:47:29.680090100+00:00
// Build No: 14154
// Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
//

#pragma once

#include <cstddef>
#include <cstdint>

#include <cstdint>

namespace exitscam {
    // Module: client.dll
    namespace buttons {
        constexpr std::ptrdiff_t attack = 0x204DA20;
        constexpr std::ptrdiff_t attack2 = 0x204DAB0;
        constexpr std::ptrdiff_t back = 0x204DCF0;
        constexpr std::ptrdiff_t duck = 0x204DFC0;
        constexpr std::ptrdiff_t forward = 0x204DC60;
        constexpr std::ptrdiff_t jump = 0x204DF30;
        constexpr std::ptrdiff_t left = 0x204DD80;
        constexpr std::ptrdiff_t lookatweapon = 0x233DCA0;
        constexpr std::ptrdiff_t reload = 0x204D990;
        constexpr std::ptrdiff_t right = 0x204DE10;
        constexpr std::ptrdiff_t showscores = 0x233DB80;
        constexpr std::ptrdiff_t sprint = 0x204D900;
        constexpr std::ptrdiff_t turnleft = 0x204DB40;
        constexpr std::ptrdiff_t turnright = 0x204DBD0;
        constexpr std::ptrdiff_t use = 0x204DEA0;
        constexpr std::ptrdiff_t zoom = 0x233DC10;
    }
}
