//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-08-20T00:07:26.459022500+00:00
// Build No: 14176
// Classes: 3330 | Enums: 549 | Offsets: 32 | Modules: 18
//

namespace ExitScam {
    // Module: client.dll
    public static class Buttons {
        public const nint attack = 0x209A000;
        public const nint attack2 = 0x209A090;
        public const nint back = 0x209A2D0;
        public const nint duck = 0x209A5A0;
        public const nint forward = 0x209A240;
        public const nint jump = 0x209A510;
        public const nint left = 0x209A360;
        public const nint lookatweapon = 0x23BFA40;
        public const nint reload = 0x2099F70;
        public const nint right = 0x209A3F0;
        public const nint showscores = 0x23BF920;
        public const nint sprint = 0x2099EE0;
        public const nint turnleft = 0x209A120;
        public const nint turnright = 0x209A1B0;
        public const nint use = 0x209A480;
        public const nint zoom = 0x23BF9B0;
    }
}
