//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-07-15T09:54:01.814225700+00:00
// Build No: 14170
// Classes: 3330 | Enums: 554 | Offsets: 32 | Modules: 18
//

#![allow(non_upper_case_globals, unused)]

pub mod exitscam {
    // Module: client.dll
    pub mod buttons {
        pub const attack: usize = 0x2093F80;
        pub const attack2: usize = 0x2094010;
        pub const back: usize = 0x2094250;
        pub const duck: usize = 0x2094520;
        pub const forward: usize = 0x20941C0;
        pub const jump: usize = 0x2094490;
        pub const left: usize = 0x20942E0;
        pub const lookatweapon: usize = 0x23B9510;
        pub const reload: usize = 0x2093EF0;
        pub const right: usize = 0x2094370;
        pub const showscores: usize = 0x23B93F0;
        pub const sprint: usize = 0x2093E60;
        pub const turnleft: usize = 0x20940A0;
        pub const turnright: usize = 0x2094130;
        pub const use: usize = 0x2094400;
        pub const zoom: usize = 0x23B9480;
    }
}
