//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-08-28T21:47:28.226030100+00:00
// Build No: 14178
// Classes: 3340 | Enums: 550 | Offsets: 32 | Modules: 18
//

#![allow(non_upper_case_globals, unused)]

pub mod exitscam {
    // Module: client.dll
    pub mod buttons {
        pub const attack: usize = 0x20B38F0;
        pub const attack2: usize = 0x20B3980;
        pub const back: usize = 0x20B3BC0;
        pub const duck: usize = 0x20B3E90;
        pub const forward: usize = 0x20B3B30;
        pub const jump: usize = 0x20B3E00;
        pub const left: usize = 0x20B3C50;
        pub const lookatweapon: usize = 0x23DBB90;
        pub const reload: usize = 0x20B3860;
        pub const right: usize = 0x20B3CE0;
        pub const showscores: usize = 0x23DBA70;
        pub const sprint: usize = 0x20B37D0;
        pub const turnleft: usize = 0x20B3A10;
        pub const turnright: usize = 0x20B3AA0;
        pub const use: usize = 0x20B3D70;
        pub const zoom: usize = 0x23DBB00;
    }
}
