//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-05-20T01:25:14.359046300+00:00
// Build No: 14162
// Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
//

namespace ExitScam {
    // Module: client.dll
    public static class Buttons {
        public const nint attack = 0x2089B10;
        public const nint attack2 = 0x2089BA0;
        public const nint back = 0x2089DE0;
        public const nint duck = 0x208A0B0;
        public const nint forward = 0x2089D50;
        public const nint jump = 0x208A020;
        public const nint left = 0x2089E70;
        public const nint lookatweapon = 0x237B4D0;
        public const nint reload = 0x2089A80;
        public const nint right = 0x2089F00;
        public const nint showscores = 0x237B3B0;
        public const nint sprint = 0x20899F0;
        public const nint turnleft = 0x2089C30;
        public const nint turnright = 0x2089CC0;
        public const nint use = 0x2089F90;
        public const nint zoom = 0x237B440;
    }
}
