//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-07-15T09:54:01.814225700+00:00
// Build No: 14170
// Classes: 3330 | Enums: 554 | Offsets: 32 | Modules: 18
//

#pragma once

#include <cstddef>
#include <cstdint>

#include <cstdint>

namespace exitscam {
    // Module: client.dll
    namespace buttons {
        constexpr std::ptrdiff_t attack = 0x2093F80;
        constexpr std::ptrdiff_t attack2 = 0x2094010;
        constexpr std::ptrdiff_t back = 0x2094250;
        constexpr std::ptrdiff_t duck = 0x2094520;
        constexpr std::ptrdiff_t forward = 0x20941C0;
        constexpr std::ptrdiff_t jump = 0x2094490;
        constexpr std::ptrdiff_t left = 0x20942E0;
        constexpr std::ptrdiff_t lookatweapon = 0x23B9510;
        constexpr std::ptrdiff_t reload = 0x2093EF0;
        constexpr std::ptrdiff_t right = 0x2094370;
        constexpr std::ptrdiff_t showscores = 0x23B93F0;
        constexpr std::ptrdiff_t sprint = 0x2093E60;
        constexpr std::ptrdiff_t turnleft = 0x20940A0;
        constexpr std::ptrdiff_t turnright = 0x2094130;
        constexpr std::ptrdiff_t use = 0x2094400;
        constexpr std::ptrdiff_t zoom = 0x23B9480;
    }
}
