//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-09-23T23:12:22.196847900+00:00
// Build No: 14183
// Classes: 3301 | Enums: 570 | Offsets: 31 | Modules: 18
//

#pragma once

#include <cstddef>
#include <cstdint>

#include <cstdint>

namespace exitscam {
    // Module: client.dll
    namespace buttons {
        constexpr std::ptrdiff_t attack = 0x222C040;
        constexpr std::ptrdiff_t attack2 = 0x222C0D0;
        constexpr std::ptrdiff_t back = 0x222C310;
        constexpr std::ptrdiff_t duck = 0x222C5E0;
        constexpr std::ptrdiff_t forward = 0x222C280;
        constexpr std::ptrdiff_t jump = 0x222C550;
        constexpr std::ptrdiff_t left = 0x222C3A0;
        constexpr std::ptrdiff_t lookatweapon = 0x25719B0;
        constexpr std::ptrdiff_t reload = 0x222BFB0;
        constexpr std::ptrdiff_t right = 0x222C430;
        constexpr std::ptrdiff_t showscores = 0x2571890;
        constexpr std::ptrdiff_t sprint = 0x222BF20;
        constexpr std::ptrdiff_t turnleft = 0x222C160;
        constexpr std::ptrdiff_t turnright = 0x222C1F0;
        constexpr std::ptrdiff_t use = 0x222C4C0;
        constexpr std::ptrdiff_t zoom = 0x2571920;
    }
}
