//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-08-25T07:01:04.153676300+00:00
// Build No: 14177
// Classes: 3340 | Enums: 550 | Offsets: 32 | Modules: 18
//

export const Buttons = {
    attack: 0x20B48F0,
    attack2: 0x20B4980,
    back: 0x20B4BC0,
    duck: 0x20B4E90,
    forward: 0x20B4B30,
    jump: 0x20B4E00,
    left: 0x20B4C50,
    lookatweapon: 0x23DCBA0,
    reload: 0x20B4860,
    right: 0x20B4CE0,
    showscores: 0x23DCA80,
    sprint: 0x20B47D0,
    turnleft: 0x20B4A10,
    turnright: 0x20B4AA0,
    use: 0x20B4D70,
    zoom: 0x23DCB10,
} as const;

