//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-04-30T02:14:22.893759300+00:00
// Build No: 14157
// Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
//

pub const exitscam = struct {
    // Module: client.dll
    pub const buttons = struct {
        pub const attack: usize = 0x204D920;
        pub const attack2: usize = 0x204D9B0;
        pub const back: usize = 0x204DBF0;
        pub const duck: usize = 0x204DEC0;
        pub const forward: usize = 0x204DB60;
        pub const jump: usize = 0x204DE30;
        pub const left: usize = 0x204DC80;
        pub const lookatweapon: usize = 0x233DBA0;
        pub const reload: usize = 0x204D890;
        pub const right: usize = 0x204DD10;
        pub const showscores: usize = 0x233DA80;
        pub const sprint: usize = 0x204D800;
        pub const turnleft: usize = 0x204DA40;
        pub const turnright: usize = 0x204DAD0;
        pub const use: usize = 0x204DDA0;
        pub const zoom: usize = 0x233DB10;
    };
};
