//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-10-08T23:59:47.471202400+00:00
// Build No: 14190
// Classes: 3301 | Enums: 568 | Offsets: 31 | Modules: 18
//

namespace ExitScam {
    // Module: client.dll
    public static class Buttons {
        public const nint attack = 0x222BED0;
        public const nint attack2 = 0x222BF60;
        public const nint back = 0x222C1A0;
        public const nint duck = 0x222C470;
        public const nint forward = 0x222C110;
        public const nint jump = 0x222C3E0;
        public const nint left = 0x222C230;
        public const nint lookatweapon = 0x2572380;
        public const nint reload = 0x222BE40;
        public const nint right = 0x222C2C0;
        public const nint showscores = 0x2572260;
        public const nint sprint = 0x222BDB0;
        public const nint turnleft = 0x222BFF0;
        public const nint turnright = 0x222C080;
        public const nint use = 0x222C350;
        public const nint zoom = 0x25722F0;
    }
}
