//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-09-24T22:07:56.824204400+00:00
// Build No: 14183
// Classes: 3301 | Enums: 570 | Offsets: 31 | Modules: 18
//

#![allow(non_upper_case_globals, unused)]

pub mod exitscam {
    // Module: client.dll
    pub mod buttons {
        pub const attack: usize = 0x222E0C0;
        pub const attack2: usize = 0x222E150;
        pub const back: usize = 0x222E390;
        pub const duck: usize = 0x222E660;
        pub const forward: usize = 0x222E300;
        pub const jump: usize = 0x222E5D0;
        pub const left: usize = 0x222E420;
        pub const lookatweapon: usize = 0x2573A60;
        pub const reload: usize = 0x222E030;
        pub const right: usize = 0x222E4B0;
        pub const showscores: usize = 0x2573940;
        pub const sprint: usize = 0x222DFA0;
        pub const turnleft: usize = 0x222E1E0;
        pub const turnright: usize = 0x222E270;
        pub const use: usize = 0x222E540;
        pub const zoom: usize = 0x25739D0;
    }
}
