//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-09-10T02:00:05.948073400+00:00
// Build No: 14181
// Classes: 3342 | Enums: 555 | Offsets: 32 | Modules: 18
//

pub const exitscam = struct {
    // Module: client.dll
    pub const buttons = struct {
        pub const attack: usize = 0x20B9B00;
        pub const attack2: usize = 0x20B9B90;
        pub const back: usize = 0x20B9DD0;
        pub const duck: usize = 0x20BA0A0;
        pub const forward: usize = 0x20B9D40;
        pub const jump: usize = 0x20BA010;
        pub const left: usize = 0x20B9E60;
        pub const lookatweapon: usize = 0x23E2530;
        pub const reload: usize = 0x20B9A70;
        pub const right: usize = 0x20B9EF0;
        pub const showscores: usize = 0x23E2410;
        pub const sprint: usize = 0x20B99E0;
        pub const turnleft: usize = 0x20B9C20;
        pub const turnright: usize = 0x20B9CB0;
        pub const use: usize = 0x20B9F80;
        pub const zoom: usize = 0x23E24A0;
    };
};
