--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-04-21T22:52:41.735496600+00:00
-- Build No: 14153
-- Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
--

return {
    client_dll = {
        attack = 0x204DA20,
        attack2 = 0x204DAB0,
        back = 0x204DCF0,
        duck = 0x204DFC0,
        forward = 0x204DC60,
        jump = 0x204DF30,
        left = 0x204DD80,
        lookatweapon = 0x233DCA0,
        reload = 0x204D990,
        right = 0x204DE10,
        showscores = 0x233DB80,
        sprint = 0x204D900,
        turnleft = 0x204DB40,
        turnright = 0x204DBD0,
        use = 0x204DEA0,
        zoom = 0x233DC10,
    }
}
