//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-05-08T04:51:02.030756300+00:00
// Build No: 14160
// Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
//

pub const exitscam = struct {
    // Module: client.dll
    pub const buttons = struct {
        pub const attack: usize = 0x204F990;
        pub const attack2: usize = 0x204FA20;
        pub const back: usize = 0x204FC60;
        pub const duck: usize = 0x204FF30;
        pub const forward: usize = 0x204FBD0;
        pub const jump: usize = 0x204FEA0;
        pub const left: usize = 0x204FCF0;
        pub const lookatweapon: usize = 0x233FB20;
        pub const reload: usize = 0x204F900;
        pub const right: usize = 0x204FD80;
        pub const showscores: usize = 0x233FA00;
        pub const sprint: usize = 0x204F870;
        pub const turnleft: usize = 0x204FAB0;
        pub const turnright: usize = 0x204FB40;
        pub const use: usize = 0x204FE10;
        pub const zoom: usize = 0x233FA90;
    };
};
