//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-08-20T00:07:26.459022500+00:00
// Build No: 14176
// Classes: 3330 | Enums: 549 | Offsets: 32 | Modules: 18
//

pub const exitscam = struct {
    pub const schemas = struct {
        // Module: host.dll
        // Class count: 2
        // Enum count: 0
        pub const host_dll = struct {
            // Parent: None
            // Field count: 1
            pub const EmptyTestScript = struct {
                pub const m_hTest: usize = 0x10; // CAnimScriptParam<float32>
            };
            // Parent: None
            // Field count: 1
            pub const CAnimScriptBase = struct {
                pub const m_bIsValid: usize = 0x8; // bool
            };
        };
    };
};
