#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-04-08T10:27:02.533990800+00:00
# Build No: 14141
# Classes: 3102 | Enums: 447 | Offsets: 32 | Modules: 18
#

# Module: animationsystem.dll
class AnimationsystemDll: {
    AnimationSystemUtils_001 = 0x7F25B8
    AnimationSystem_001 = 0x7EA4D0
}
# Module: client.dll
class ClientDll: {
    ClientToolsInfo_001 = 0x2065F90
    EmptyWorldService001_Client = 0x201FE50
    GameClientExports001 = 0x2062C70
    LegacyGameUI001 = 0x20804D0
    Source2Client002 = 0x230CDD0
    Source2ClientConfig001 = 0x2290F00
    Source2ClientPrediction001 = 0x206D8F0
    Source2ClientUI001 = 0x207ED60
}
# Module: engine2.dll
class Engine2Dll: {
    BenchmarkService001 = 0x614930
    BugService001 = 0x8C9E10
    ClientServerEngineLoopService_001 = 0x90B4B0
    EngineGameUI001 = 0x6122E0
    EngineServiceMgr001 = 0x90AD60
    GameEventSystemClientV001 = 0x90B040
    GameEventSystemServerV001 = 0x90B170
    GameResourceServiceClientV001 = 0x614A30
    GameResourceServiceServerV001 = 0x614A90
    GameUIService_001 = 0x8CA240
    HostStateMgr001 = 0x6152B0
    INETSUPPORT_001 = 0x60D8E0
    InputService_001 = 0x8CA530
    KeyValueCache001 = 0x615360
    MapListService_001 = 0x9093A0
    NetworkClientService_001 = 0x909530
    NetworkP2PService_001 = 0x909870
    NetworkServerService_001 = 0x909A20
    NetworkService_001 = 0x614C00
    RenderService_001 = 0x909C90
    ScreenshotService001 = 0x909F50
    SimpleEngineLoopService_001 = 0x6153C0
    SoundService_001 = 0x614C40
    Source2EngineToClient001 = 0x611BE0
    Source2EngineToClientStringTable001 = 0x611C40
    Source2EngineToServer001 = 0x611CB8
    Source2EngineToServerStringTable001 = 0x611CE0
    SplitScreenService_001 = 0x614F20
    StatsService_001 = 0x90A310
    ToolService_001 = 0x6150E0
    VENGINE_GAMEUIFUNCS_VERSION005 = 0x612370
    VProfService_001 = 0x615120
}
# Module: filesystem_stdio.dll
class FilesystemStdioDll: {
    VAsyncFileSystem2_001 = 0x214970
    VFileSystem017 = 0x214730
}
# Module: host.dll
class HostDll: {
    DebugDrawQueueManager001 = 0x139020
    GameModelInfo001 = 0x139060
    GameSystem2HostHook = 0x1390A0
    HostUtils001 = 0x1467E0
    PredictionDiffManager001 = 0x1391B0
    SaveRestoreDataVersion001 = 0x1392E0
    SinglePlayerSharedMemory001 = 0x139310
    Source2Host001 = 0x139380
}
# Module: imemanager.dll
class ImemanagerDll: {
    IMEManager001 = 0x36AA0
}
# Module: inputsystem.dll
class InputsystemDll: {
    InputStackSystemVersion001 = 0x43DD0
    InputSystemVersion001 = 0x45AD0
}
# Module: localize.dll
class LocalizeDll: {
    Localize_001 = 0x57E20
}
# Module: matchmaking.dll
class MatchmakingDll: {
    GameTypes001 = 0x1B8000
    MATCHFRAMEWORK_001 = 0x1C02B0
}
# Module: materialsystem2.dll
class Materialsystem2Dll: {
    FontManager_001 = 0x164570
    MaterialUtils_001 = 0x14C5C0
    PostProcessingSystem_001 = 0x14C4D0
    TextLayout_001 = 0x14C550
    VMaterialSystem2_001 = 0x163E80
}
# Module: meshsystem.dll
class MeshsystemDll: {
    MeshSystem001 = 0x1506A0
}
# Module: navsystem.dll
class NavsystemDll: {
    NavSystem001 = 0x1269E0
}
# Module: networksystem.dll
class NetworksystemDll: {
    FlattenedSerializersVersion001 = 0x27B7C0
    NetworkMessagesVersion001 = 0x2A3950
    NetworkSystemVersion001 = 0x294F80
    SerializedEntitiesVersion001 = 0x295070
}
# Module: panorama.dll
class PanoramaDll: {
    PanoramaUIEngine001 = 0x507CB0
}
# Module: panorama_text_pango.dll
class PanoramaTextPangoDll: {
    PanoramaTextServices001 = 0x2B89C0
}
# Module: panoramauiclient.dll
class PanoramauiclientDll: {
    PanoramaUIClient001 = 0x295380
}
# Module: particles.dll
class ParticlesDll: {
    ParticleSystemMgr003 = 0x520E70
}
# Module: pulse_system.dll
class PulseSystemDll: {
    IPulseSystem_001 = 0x1F2670
}
# Module: rendersystemdx11.dll
class Rendersystemdx11Dll: {
    RenderDeviceMgr001 = 0x432D30
    RenderUtils_001 = 0x433628
    VRenderDeviceMgrBackdoor001 = 0x432DD0
}
# Module: resourcesystem.dll
class ResourcesystemDll: {
    ResourceSystem013 = 0x81FE0
}
# Module: scenefilecache.dll
class ScenefilecacheDll: {
    ResponseRulesCache001 = 0xDB190
    SceneFileCache002 = 0xDB2C0
}
# Module: scenesystem.dll
class ScenesystemDll: {
    RenderingPipelines_001 = 0x65BAD0
    SceneSystem_002 = 0x8CFEE0
    SceneUtils_001 = 0x65C9E0
}
# Module: schemasystem.dll
class SchemasystemDll: {
    SchemaSystem_001 = 0x76730
}
# Module: server.dll
class ServerDll: {
    EmptyWorldService001_Server = 0x1B78A90
    EntitySubclassUtilsV001 = 0x1B24160
    NavGameTest001 = 0x1C226D8
    ServerToolsInfo_001 = 0x1BD3978
    Source2GameClients001 = 0x1BD09F0
    Source2GameDirector001 = 0x1D628D0
    Source2GameEntities001 = 0x1BD3080
    Source2Server001 = 0x1BD2EE0
    Source2ServerConfig001 = 0x1E57B18
    customnavsystem001 = 0x1B02F58
}
# Module: soundsystem.dll
class SoundsystemDll: {
    SoundOpSystem001 = 0x4F3AA0
    SoundOpSystemEdit001 = 0x4F3980
    SoundSystem001 = 0x4F3470
    VMixEditTool001 = 0x59472FF
}
# Module: steamaudio.dll
class SteamaudioDll: {
    SteamAudio001 = 0x25C440
}
# Module: steamclient64.dll
class Steamclient64Dll: {
    IVALIDATE001 = 0x16998B8
    SteamClient006 = 0x1696D50
    SteamClient007 = 0x1696D58
    SteamClient008 = 0x1696D60
    SteamClient009 = 0x1696D68
    SteamClient010 = 0x1696D70
    SteamClient011 = 0x1696D78
    SteamClient012 = 0x1696D80
    SteamClient013 = 0x1696D88
    SteamClient014 = 0x1696D90
    SteamClient015 = 0x1696D98
    SteamClient016 = 0x1696DA0
    SteamClient017 = 0x1696DA8
    SteamClient018 = 0x1696DB0
    SteamClient019 = 0x1696DB8
    SteamClient020 = 0x1696DC0
    SteamClient021 = 0x1696DC8
    SteamClient022 = 0x1696DD0
    SteamClient023 = 0x1696DD8
    p2pvoice002 = 0x14E5DEF
    p2pvoicesingleton002 = 0x16720F0
}
# Module: tier0.dll
class Tier0Dll: {
    TestScriptMgr001 = 0x398620
    VEngineCvar007 = 0x3A33B0
    VProcessUtils002 = 0x3985C0
    VStringTokenSystem001 = 0x3CA090
}
# Module: v8system.dll
class V8systemDll: {
    Source2V8System001 = 0x316B0
}
# Module: vphysics2.dll
class Vphysics2Dll: {
    VPhysics2_Handle_Interface_001 = 0x4000E0
    VPhysics2_Interface_001 = 0x400120
}
# Module: vscript.dll
class VscriptDll: {
    VScriptManager010 = 0x13B390
}
# Module: vstdlib_s64.dll
class VstdlibS64Dll: {
    IVALIDATE001 = 0x6F990
    VEngineCvar002 = 0x6E070
}
# Module: worldrenderer.dll
class WorldrendererDll: {
    WorldRendererMgr001 = 0x214A00
}
