--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-09-24T22:07:56.824204400+00:00
-- Build No: 14183
-- Classes: 3301 | Enums: 570 | Offsets: 31 | Modules: 18
--

return {
    animationsystem_dll = {
        AnimationSystemUtils_001 = 0x83F6D8,
        AnimationSystem_001 = 0x8375F8,
    },
    client_dll = {
        ClientBugBugServic001_Client = 0x222D8D0,
        ClientToolsInfo_001 = 0x222D8A0,
        EmptyWorldService001_Client = 0x2211370,
        GameClientExports001 = 0x222A548,
        LegacyGameUI001 = 0x223A1E0,
        Source2Client002 = 0x2557DC0,
        Source2ClientConfig001 = 0x24B4B20,
        Source2ClientPrediction001 = 0x255E560,
        Source2ClientUI001 = 0x2238A50,
    },
    engine2_dll = {
        BenchmarkService001 = 0x622E80,
        BugBugService001 = 0x622F80,
        BugService001 = 0x8DB9F0,
        ClientServerEngineLoopService_001 = 0x91D030,
        ClientServerSharedHandleSystem001 = 0x91C640,
        EngineGameUI001 = 0x6208E0,
        EngineServiceMgr001 = 0x91C900,
        GameEventSystemClientV001 = 0x91CBE0,
        GameEventSystemServerV001 = 0x91CD10,
        GameResourceServiceClientV001 = 0x622FC0,
        GameResourceServiceServerV001 = 0x623020,
        GameUIService_001 = 0x8DBE40,
        HostStateMgr001 = 0x623740,
        INETSUPPORT_001 = 0x61BE30,
        InputService_001 = 0x8DC120,
        KeyValueCache001 = 0x6237F0,
        MapListService_001 = 0x91AF90,
        NetworkClientService_001 = 0x91B120,
        NetworkP2PService_001 = 0x91B460,
        NetworkServerService_001 = 0x91B610,
        NetworkService_001 = 0x623190,
        RenderService_001 = 0x91B880,
        ScreenshotService001 = 0x91BB40,
        SimpleEngineLoopService_001 = 0x623850,
        SoundService_001 = 0x6231D0,
        Source2EngineToClient001 = 0x6201F0,
        Source2EngineToClientStringTable001 = 0x620250,
        Source2EngineToServer001 = 0x6202C8,
        Source2EngineToServerStringTable001 = 0x6202F0,
        SplitScreenService_001 = 0x6234B0,
        StatsService_001 = 0x91BE80,
        ToolService_001 = 0x6235B0,
        VENGINE_GAMEUIFUNCS_VERSION005 = 0x620970,
        VProfService_001 = 0x6235F0,
    },
    filesystem_stdio_dll = {
        VAsyncFileSystem2_001 = 0x214610,
        VFileSystem017 = 0x2143D0,
    },
    host_dll = {
        DebugDrawQueueManager001 = 0x13FF70,
        GameModelInfo001 = 0x13FFB0,
        GameSystem2HostHook = 0x13FFF0,
        HostUtils001 = 0x14F900,
        PredictionDiffManager001 = 0x140100,
        SaveRestoreDataVersion001 = 0x140230,
        SinglePlayerSharedMemory001 = 0x140260,
        Source2Host001 = 0x1402D0,
    },
    imemanager_dll = {
        IMEManager001 = 0x37AA0,
    },
    inputsystem_dll = {
        InputStackSystemVersion001 = 0x44E90,
        InputSystemVersion001 = 0x46BC0,
    },
    localize_dll = {
        Localize_001 = 0x59120,
    },
    matchmaking_dll = {
        GameTypes001 = 0x1B0FD0,
        MATCHFRAMEWORK_001 = 0x1B90A0,
    },
    materialsystem2_dll = {
        FontManager_001 = 0x163AE0,
        MaterialUtils_001 = 0x14BF30,
        PostProcessingSystem_001 = 0x14BE60,
        TextLayout_001 = 0x14BEC0,
        VMaterialSystem2_001 = 0x163730,
    },
    meshsystem_dll = {
        MeshSystem001 = 0x180AB0,
    },
    navsystem_dll = {
        NavSystem001 = 0x12C000,
    },
    networksystem_dll = {
        FlattenedSerializersVersion001 = 0x277A50,
        NetworkMessagesVersion001 = 0x2A3F10,
        NetworkSystemVersion001 = 0x2911A0,
        SerializedEntitiesVersion001 = 0x291290,
    },
    panorama_dll = {
        PanoramaUIEngine001 = 0x587160,
    },
    panorama_text_pango_dll = {
        PanoramaTextServices001 = 0x2BA9D0,
    },
    panoramauiclient_dll = {
        PanoramaUIClient001 = 0x26F090,
    },
    particles_dll = {
        ParticleSystemMgr003 = 0x65AEF0,
    },
    pulse_system_dll = {
        IPulseSystem_001 = 0x238120,
    },
    rendersystemdx11_dll = {
        RenderDeviceMgr001 = 0x4344D0,
        RenderUtils_001 = 0x434DB0,
        VRenderDeviceMgrBackdoor001 = 0x434570,
    },
    resourcesystem_dll = {
        ResourceSystem013 = 0x892A0,
    },
    scenefilecache_dll = {
        ResponseRulesCache001 = 0x11D350,
        SceneFileCache002 = 0x11D478,
    },
    scenesystem_dll = {
        RenderingPipelines_001 = 0x675C00,
        SceneSystem_002 = 0x91FCE0,
        SceneUtils_001 = 0x676960,
    },
    schemasystem_dll = {
        SchemaSystem_001 = 0x76710,
    },
    server_dll = {
        EmptyWorldService001_Server = 0x1E0B290,
        EntitySubclassUtilsV001 = 0x1DBABF0,
        NavGameTest001 = 0x1E52ED0,
        ServerToolsInfo_001 = 0x1E31DD8,
        Source2GameClients001 = 0x1E31300,
        Source2GameDirector001 = 0x1F9B570,
        Source2GameEntities001 = 0x1E31580,
        Source2Server001 = 0x1E313C0,
        Source2ServerConfig001 = 0x2116E68,
        customnavsystem001 = 0x1DA8508,
    },
    soundsystem_dll = {
        SoundBugBugService001_Client = 0x535BA0,
        SoundOpSystem001 = 0x535A80,
        SoundOpSystemEdit001 = 0x535990,
        SoundSystem001 = 0x535340,
        VMixEditTool001 = 0x5943D7F,
    },
    steamaudio_dll = {
        SteamAudio001 = 0x35C1A0,
    },
    tier0_dll = {
        TestScriptMgr001 = 0x3A1960,
        VEngineCvar007 = 0x3AC670,
        VProcessUtils002 = 0x3A1820,
        VStringTokenSystem001 = 0x3D3300,
    },
    v8system_dll = {
        Source2V8System001 = 0x34790,
    },
    vconcomm_dll = {
        VConComm001 = 0x3C750,
    },
    vphysics2_dll = {
        VPhysics2_Interface_001 = 0x460E70,
    },
    vscript_dll = {
        VScriptManager010 = 0x13E430,
    },
    worldrenderer_dll = {
        WorldRendererMgr001 = 0x236F60,
    },
}
