//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-10-08T23:59:47.471202400+00:00
// Build No: 14190
// Classes: 3301 | Enums: 568 | Offsets: 31 | Modules: 18
//

export const Interfaces = {
    animationsystem_dll : {
        AnimationSystemUtils_001 : 0x83F6D8,
        AnimationSystem_001 : 0x8375F8,
    },
    client_dll : {
        ClientBugBugServic001_Client : 0x222B6E0,
        ClientToolsInfo_001 : 0x222B6B0,
        EmptyWorldService001_Client : 0x220F100,
        GameClientExports001 : 0x2228358,
        LegacyGameUI001 : 0x2238010,
        Source2Client002 : 0x25560E0,
        Source2ClientConfig001 : 0x24B2C90,
        Source2ClientPrediction001 : 0x255C2D0,
        Source2ClientUI001 : 0x2236890,
    },
    engine2_dll : {
        BenchmarkService001 : 0x622C80,
        BugBugService001 : 0x622D80,
        BugService001 : 0x8DB7F0,
        ClientServerEngineLoopService_001 : 0x91CE30,
        ClientServerSharedHandleSystem001 : 0x91C440,
        EngineGameUI001 : 0x6206E0,
        EngineServiceMgr001 : 0x91C700,
        GameEventSystemClientV001 : 0x91C9E0,
        GameEventSystemServerV001 : 0x91CB10,
        GameResourceServiceClientV001 : 0x622DC0,
        GameResourceServiceServerV001 : 0x622E20,
        GameUIService_001 : 0x8DBC40,
        HostStateMgr001 : 0x623540,
        INETSUPPORT_001 : 0x61BC30,
        InputService_001 : 0x8DBF20,
        KeyValueCache001 : 0x6235F0,
        MapListService_001 : 0x91AD90,
        NetworkClientService_001 : 0x91AF20,
        NetworkP2PService_001 : 0x91B260,
        NetworkServerService_001 : 0x91B410,
        NetworkService_001 : 0x622F90,
        RenderService_001 : 0x91B680,
        ScreenshotService001 : 0x91B940,
        SimpleEngineLoopService_001 : 0x623650,
        SoundService_001 : 0x622FD0,
        Source2EngineToClient001 : 0x61FFF0,
        Source2EngineToClientStringTable001 : 0x620050,
        Source2EngineToServer001 : 0x6200C8,
        Source2EngineToServerStringTable001 : 0x6200F0,
        SplitScreenService_001 : 0x6232B0,
        StatsService_001 : 0x91BC80,
        ToolService_001 : 0x6233B0,
        VENGINE_GAMEUIFUNCS_VERSION005 : 0x620770,
        VProfService_001 : 0x6233F0,
    },
    filesystem_stdio_dll : {
        VAsyncFileSystem2_001 : 0x214610,
        VFileSystem017 : 0x2143D0,
    },
    host_dll : {
        DebugDrawQueueManager001 : 0x13FF70,
        GameModelInfo001 : 0x13FFB0,
        GameSystem2HostHook : 0x13FFF0,
        HostUtils001 : 0x14F900,
        PredictionDiffManager001 : 0x140100,
        SaveRestoreDataVersion001 : 0x140230,
        SinglePlayerSharedMemory001 : 0x140260,
        Source2Host001 : 0x1402D0,
    },
    imemanager_dll : {
        IMEManager001 : 0x37AA0,
    },
    inputsystem_dll : {
        InputStackSystemVersion001 : 0x44E90,
        InputSystemVersion001 : 0x46BC0,
    },
    localize_dll : {
        Localize_001 : 0x59120,
    },
    matchmaking_dll : {
        GameTypes001 : 0x1B0FD0,
        MATCHFRAMEWORK_001 : 0x1B90A0,
    },
    materialsystem2_dll : {
        FontManager_001 : 0x1638E0,
        MaterialUtils_001 : 0x14BD30,
        PostProcessingSystem_001 : 0x14BC60,
        TextLayout_001 : 0x14BCC0,
        VMaterialSystem2_001 : 0x163530,
    },
    meshsystem_dll : {
        MeshSystem001 : 0x180AB0,
    },
    navsystem_dll : {
        NavSystem001 : 0x12C000,
    },
    networksystem_dll : {
        FlattenedSerializersVersion001 : 0x277A50,
        NetworkMessagesVersion001 : 0x2A3F30,
        NetworkSystemVersion001 : 0x2911A0,
        SerializedEntitiesVersion001 : 0x291290,
    },
    panorama_dll : {
        PanoramaUIEngine001 : 0x5895F0,
    },
    panorama_text_pango_dll : {
        PanoramaTextServices001 : 0x2BA9D0,
    },
    panoramauiclient_dll : {
        PanoramaUIClient001 : 0x270710,
    },
    particles_dll : {
        ParticleSystemMgr003 : 0x65AEB0,
    },
    pulse_system_dll : {
        IPulseSystem_001 : 0x238120,
    },
    rendersystemdx11_dll : {
        RenderDeviceMgr001 : 0x4342F0,
        RenderUtils_001 : 0x434BD0,
        VRenderDeviceMgrBackdoor001 : 0x434390,
    },
    resourcesystem_dll : {
        ResourceSystem013 : 0x892B0,
    },
    scenefilecache_dll : {
        ResponseRulesCache001 : 0x11D350,
        SceneFileCache002 : 0x11D478,
    },
    scenesystem_dll : {
        RenderingPipelines_001 : 0x675A00,
        SceneSystem_002 : 0x91FB20,
        SceneUtils_001 : 0x676760,
    },
    schemasystem_dll : {
        SchemaSystem_001 : 0x76710,
    },
    server_dll : {
        EmptyWorldService001_Server : 0x1E03070,
        EntitySubclassUtilsV001 : 0x1DB2C20,
        NavGameTest001 : 0x1E4ACA8,
        ServerToolsInfo_001 : 0x1E29BC8,
        Source2GameClients001 : 0x1E290F0,
        Source2GameDirector001 : 0x1F930F0,
        Source2GameEntities001 : 0x1E29370,
        Source2Server001 : 0x1E291B0,
        Source2ServerConfig001 : 0x210E998,
        customnavsystem001 : 0x1DA0528,
    },
    soundsystem_dll : {
        SoundBugBugService001_Client : 0x535BB0,
        SoundOpSystem001 : 0x535A90,
        SoundOpSystemEdit001 : 0x5359A0,
        SoundSystem001 : 0x535350,
        VMixEditTool001 : 0x5943D7F,
    },
    steamaudio_dll : {
        SteamAudio001 : 0x35C1A0,
    },
    tier0_dll : {
        TestScriptMgr001 : 0x3A1960,
        VEngineCvar007 : 0x3AC670,
        VProcessUtils002 : 0x3A1820,
        VStringTokenSystem001 : 0x3D3300,
    },
    v8system_dll : {
        Source2V8System001 : 0x34790,
    },
    vconcomm_dll : {
        VConComm001 : 0x3C750,
    },
    vphysics2_dll : {
        VPhysics2_Interface_001 : 0x460E60,
    },
    vscript_dll : {
        VScriptManager010 : 0x13E430,
    },
    worldrenderer_dll : {
        WorldRendererMgr001 : 0x236D00,
    },
} as const;

