#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-09-10T02:00:05.948073400+00:00
# Build No: 14181
# Classes: 3342 | Enums: 555 | Offsets: 32 | Modules: 18
#

# Module: animationsystem.dll
class AnimationsystemDll: {
    AnimationSystemUtils_001 = 0x837F10
    AnimationSystem_001 = 0x82FE30
}
# Module: client.dll
class ClientDll: {
    ClientBugBugServic001_Client = 0x20B9310
    ClientToolsInfo_001 = 0x20B92E0
    EmptyWorldService001_Client = 0x2095950
    GameClientExports001 = 0x20B5F80
    LegacyGameUI001 = 0x20C9870
    Source2Client002 = 0x23C73C0
    Source2ClientConfig001 = 0x2338290
    Source2ClientPrediction001 = 0x23CCB10
    Source2ClientUI001 = 0x20C7D80
}
# Module: engine2.dll
class Engine2Dll: {
    BenchmarkService001 = 0x616360
    BugBugService001 = 0x616460
    BugService001 = 0x8CEEC0
    ClientServerEngineLoopService_001 = 0x9105C0
    ClientServerSharedHandleSystem001 = 0x90FB90
    EngineGameUI001 = 0x613C80
    EngineServiceMgr001 = 0x90FEA0
    GameEventSystemClientV001 = 0x910180
    GameEventSystemServerV001 = 0x9102B0
    GameResourceServiceClientV001 = 0x6164A0
    GameResourceServiceServerV001 = 0x616500
    GameUIService_001 = 0x8CF310
    HostStateMgr001 = 0x616CE0
    INETSUPPORT_001 = 0x60F970
    InputService_001 = 0x8CF600
    KeyValueCache001 = 0x616D90
    MapListService_001 = 0x90E470
    NetworkClientService_001 = 0x90E600
    NetworkP2PService_001 = 0x90E940
    NetworkServerService_001 = 0x90EAF0
    NetworkService_001 = 0x616670
    RenderService_001 = 0x90ED60
    ScreenshotService001 = 0x90F020
    SimpleEngineLoopService_001 = 0x616DF0
    SoundService_001 = 0x6166B0
    Source2EngineToClient001 = 0x6135B0
    Source2EngineToClientStringTable001 = 0x613610
    Source2EngineToServer001 = 0x613688
    Source2EngineToServerStringTable001 = 0x6136B0
    SplitScreenService_001 = 0x616990
    StatsService_001 = 0x90F3E0
    ToolService_001 = 0x616B50
    VENGINE_GAMEUIFUNCS_VERSION005 = 0x613D10
    VProfService_001 = 0x616B90
}
# Module: filesystem_stdio.dll
class FilesystemStdioDll: {
    VAsyncFileSystem2_001 = 0x213600
    VFileSystem017 = 0x2133C0
}
# Module: host.dll
class HostDll: {
    DebugDrawQueueManager001 = 0x13E0A0
    GameModelInfo001 = 0x13E0E0
    GameSystem2HostHook = 0x13E120
    HostUtils001 = 0x14DB50
    PredictionDiffManager001 = 0x13E230
    SaveRestoreDataVersion001 = 0x13E360
    SinglePlayerSharedMemory001 = 0x13E390
    Source2Host001 = 0x13E400
}
# Module: imemanager.dll
class ImemanagerDll: {
    IMEManager001 = 0x36AA0
}
# Module: inputsystem.dll
class InputsystemDll: {
    InputStackSystemVersion001 = 0x43E90
    InputSystemVersion001 = 0x45BA0
}
# Module: localize.dll
class LocalizeDll: {
    Localize_001 = 0x58100
}
# Module: matchmaking.dll
class MatchmakingDll: {
    GameTypes001 = 0x1ADF80
    MATCHFRAMEWORK_001 = 0x1B6020
}
# Module: materialsystem2.dll
class Materialsystem2Dll: {
    FontManager_001 = 0x15CBB0
    MaterialUtils_001 = 0x144F00
    PostProcessingSystem_001 = 0x144E30
    TextLayout_001 = 0x144E90
    VMaterialSystem2_001 = 0x15C800
}
# Module: meshsystem.dll
class MeshsystemDll: {
    MeshSystem001 = 0x16BDE0
}
# Module: navsystem.dll
class NavsystemDll: {
    NavSystem001 = 0x128C20
}
# Module: networksystem.dll
class NetworksystemDll: {
    FlattenedSerializersVersion001 = 0x26C840
    NetworkMessagesVersion001 = 0x298AC0
    NetworkSystemVersion001 = 0x285F90
    SerializedEntitiesVersion001 = 0x286080
}
# Module: panorama.dll
class PanoramaDll: {
    PanoramaUIEngine001 = 0x50FD60
}
# Module: panorama_text_pango.dll
class PanoramaTextPangoDll: {
    PanoramaTextServices001 = 0x2B89D0
}
# Module: panoramauiclient.dll
class PanoramauiclientDll: {
    PanoramaUIClient001 = 0x295210
}
# Module: particles.dll
class ParticlesDll: {
    ParticleSystemMgr003 = 0x5FEAC0
}
# Module: pulse_system.dll
class PulseSystemDll: {
    IPulseSystem_001 = 0x219750
}
# Module: rendersystemdx11.dll
class Rendersystemdx11Dll: {
    RenderDeviceMgr001 = 0x42C550
    RenderUtils_001 = 0x42CE30
    VRenderDeviceMgrBackdoor001 = 0x42C5F0
}
# Module: resourcesystem.dll
class ResourcesystemDll: {
    ResourceSystem013 = 0x81680
}
# Module: scenefilecache.dll
class ScenefilecacheDll: {
    ResponseRulesCache001 = 0x113450
    SceneFileCache002 = 0x113578
}
# Module: scenesystem.dll
class ScenesystemDll: {
    RenderingPipelines_001 = 0x667F10
    SceneSystem_002 = 0x911530
    SceneUtils_001 = 0x668DD0
}
# Module: schemasystem.dll
class SchemasystemDll: {
    SchemaSystem_001 = 0x75730
}
# Module: server.dll
class ServerDll: {
    EmptyWorldService001_Server = 0x1C70470
    EntitySubclassUtilsV001 = 0x1C1EAE0
    NavGameTest001 = 0x1CE2C60
    ServerToolsInfo_001 = 0x1CA9538
    Source2GameClients001 = 0x1CA8720
    Source2GameDirector001 = 0x1E2ACE0
    Source2GameEntities001 = 0x1CA8CE0
    Source2Server001 = 0x1CA8B30
    Source2ServerConfig001 = 0x1F99D98
    customnavsystem001 = 0x1C02F28
}
# Module: soundsystem.dll
class SoundsystemDll: {
    SoundBugBugService001_Client = 0x54BD80
    SoundOpSystem001 = 0x54BC60
    SoundOpSystemEdit001 = 0x54BB70
    SoundSystem001 = 0x54B5D0
    VMixEditTool001 = 0x594945F
}
# Module: steamaudio.dll
class SteamaudioDll: {
    SteamAudio001 = 0x260610
}
# Module: tier0.dll
class Tier0Dll: {
    TestScriptMgr001 = 0x39A800
    VEngineCvar007 = 0x3A54F0
    VProcessUtils002 = 0x39A7A0
    VStringTokenSystem001 = 0x3CC1F0
}
# Module: v8system.dll
class V8systemDll: {
    Source2V8System001 = 0x31770
}
# Module: vphysics2.dll
class Vphysics2Dll: {
    VPhysics2_Interface_001 = 0x428E90
}
# Module: vscript.dll
class VscriptDll: {
    VScriptManager010 = 0x13D430
}
# Module: worldrenderer.dll
class WorldrendererDll: {
    WorldRendererMgr001 = 0x231DA0
}
