--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-04-21T01:07:42.863545+00:00
-- Build No: 14151
-- Classes: 3222 | Enums: 480 | Offsets: 32 | Modules: 18
--

return {
    animationsystem_dll = {
        AnimationSystemUtils_001 = 0x812190,
        AnimationSystem_001 = 0x80A0B0,
    },
    client_dll = {
        ClientToolsInfo_001 = 0x20480D0,
        EmptyWorldService001_Client = 0x200BAA0,
        GameClientExports001 = 0x2044D70,
        LegacyGameUI001 = 0x2060480,
        Source2Client002 = 0x231E850,
        Source2ClientConfig001 = 0x2290B80,
        Source2ClientPrediction001 = 0x204F540,
        Source2ClientUI001 = 0x205EA70,
    },
    engine2_dll = {
        BenchmarkService001 = 0x612950,
        BugService001 = 0x8CA900,
        ClientServerEngineLoopService_001 = 0x90C000,
        ClientServerSharedHandleSystem001 = 0x90B5B0,
        EngineGameUI001 = 0x6102A0,
        EngineServiceMgr001 = 0x90B8E0,
        GameEventSystemClientV001 = 0x90BBC0,
        GameEventSystemServerV001 = 0x90BCF0,
        GameResourceServiceClientV001 = 0x612A50,
        GameResourceServiceServerV001 = 0x612AB0,
        GameUIService_001 = 0x8CAD30,
        HostStateMgr001 = 0x613290,
        INETSUPPORT_001 = 0x60C040,
        InputService_001 = 0x8CB020,
        KeyValueCache001 = 0x613340,
        MapListService_001 = 0x909E90,
        NetworkClientService_001 = 0x90A020,
        NetworkP2PService_001 = 0x90A360,
        NetworkServerService_001 = 0x90A510,
        NetworkService_001 = 0x612C20,
        RenderService_001 = 0x90A780,
        ScreenshotService001 = 0x90AA40,
        SimpleEngineLoopService_001 = 0x6133A0,
        SoundService_001 = 0x612C60,
        Source2EngineToClient001 = 0x60FBA0,
        Source2EngineToClientStringTable001 = 0x60FC00,
        Source2EngineToServer001 = 0x60FC78,
        Source2EngineToServerStringTable001 = 0x60FCA0,
        SplitScreenService_001 = 0x612F40,
        StatsService_001 = 0x90AE00,
        ToolService_001 = 0x613100,
        VENGINE_GAMEUIFUNCS_VERSION005 = 0x610330,
        VProfService_001 = 0x613140,
    },
    filesystem_stdio_dll = {
        VAsyncFileSystem2_001 = 0x2159E0,
        VFileSystem017 = 0x2157A0,
    },
    host_dll = {
        DebugDrawQueueManager001 = 0x139060,
        GameModelInfo001 = 0x1390A0,
        GameSystem2HostHook = 0x1390E0,
        HostUtils001 = 0x148AB0,
        PredictionDiffManager001 = 0x1391F0,
        SaveRestoreDataVersion001 = 0x139320,
        SinglePlayerSharedMemory001 = 0x139350,
        Source2Host001 = 0x1393C0,
    },
    imemanager_dll = {
        IMEManager001 = 0x36B20,
    },
    inputsystem_dll = {
        InputStackSystemVersion001 = 0x40E30,
        InputSystemVersion001 = 0x42B50,
    },
    localize_dll = {
        Localize_001 = 0x62180,
    },
    matchmaking_dll = {
        GameTypes001 = 0x1B0F80,
        MATCHFRAMEWORK_001 = 0x1B9060,
    },
    materialsystem2_dll = {
        FontManager_001 = 0x15DE60,
        MaterialUtils_001 = 0x145D40,
        PostProcessingSystem_001 = 0x145C50,
        TextLayout_001 = 0x145CD0,
        VMaterialSystem2_001 = 0x15D750,
    },
    meshsystem_dll = {
        MeshSystem001 = 0x150C20,
    },
    navsystem_dll = {
        NavSystem001 = 0x122930,
    },
    networksystem_dll = {
        FlattenedSerializersVersion001 = 0x26D700,
        NetworkMessagesVersion001 = 0x2959D0,
        NetworkSystemVersion001 = 0x286E50,
        SerializedEntitiesVersion001 = 0x286F40,
    },
    panorama_dll = {
        PanoramaUIEngine001 = 0x505D30,
    },
    panorama_text_pango_dll = {
        PanoramaTextServices001 = 0x2B8A40,
    },
    panoramauiclient_dll = {
        PanoramaUIClient001 = 0x296420,
    },
    particles_dll = {
        ParticleSystemMgr003 = 0x54A3C0,
    },
    pulse_system_dll = {
        IPulseSystem_001 = 0x1F36A0,
    },
    rendersystemdx11_dll = {
        RenderDeviceMgr001 = 0x42B530,
        RenderUtils_001 = 0x42BE28,
        VRenderDeviceMgrBackdoor001 = 0x42B5D0,
    },
    resourcesystem_dll = {
        ResourceSystem013 = 0x831E0,
    },
    scenefilecache_dll = {
        ResponseRulesCache001 = 0xF58F0,
        SceneFileCache002 = 0xF5A78,
    },
    scenesystem_dll = {
        RenderingPipelines_001 = 0x663B80,
        SceneSystem_002 = 0x8DB470,
        SceneUtils_001 = 0x664A90,
    },
    schemasystem_dll = {
        SchemaSystem_001 = 0x76800,
    },
    server_dll = {
        EmptyWorldService001_Server = 0x1BEBCE0,
        EntitySubclassUtilsV001 = 0x1B97350,
        NavGameTest001 = 0x1C98110,
        ServerToolsInfo_001 = 0x1C45418,
        Source2GameClients001 = 0x1C43E70,
        Source2GameDirector001 = 0x1DDD4E0,
        Source2GameEntities001 = 0x1C44B20,
        Source2Server001 = 0x1C44970,
        Source2ServerConfig001 = 0x1EFA788,
        customnavsystem001 = 0x1B78658,
    },
    soundsystem_dll = {
        SoundOpSystem001 = 0x5129B0,
        SoundOpSystemEdit001 = 0x512870,
        SoundSystem001 = 0x512360,
        VMixEditTool001 = 0x594879F,
    },
    steamaudio_dll = {
        SteamAudio001 = 0x25E620,
    },
    steamclient64_dll = {
        IVALIDATE001 = 0x16998B8,
        SteamClient006 = 0x1696D50,
        SteamClient007 = 0x1696D58,
        SteamClient008 = 0x1696D60,
        SteamClient009 = 0x1696D68,
        SteamClient010 = 0x1696D70,
        SteamClient011 = 0x1696D78,
        SteamClient012 = 0x1696D80,
        SteamClient013 = 0x1696D88,
        SteamClient014 = 0x1696D90,
        SteamClient015 = 0x1696D98,
        SteamClient016 = 0x1696DA0,
        SteamClient017 = 0x1696DA8,
        SteamClient018 = 0x1696DB0,
        SteamClient019 = 0x1696DB8,
        SteamClient020 = 0x1696DC0,
        SteamClient021 = 0x1696DC8,
        SteamClient022 = 0x1696DD0,
        SteamClient023 = 0x1696DD8,
        p2pvoice002 = 0x14E5DEF,
        p2pvoicesingleton002 = 0x16720F0,
    },
    tier0_dll = {
        TestScriptMgr001 = 0x39E6F0,
        VEngineCvar007 = 0x3A93B0,
        VProcessUtils002 = 0x39E690,
        VStringTokenSystem001 = 0x3D00B0,
    },
    v8system_dll = {
        Source2V8System001 = 0x31730,
    },
    vphysics2_dll = {
        VPhysics2_Interface_001 = 0x40DDA0,
    },
    vscript_dll = {
        VScriptManager010 = 0x13B410,
    },
    vstdlib_s64_dll = {
        IVALIDATE001 = 0x6F990,
        VEngineCvar002 = 0x6E070,
    },
    worldrenderer_dll = {
        WorldRendererMgr001 = 0x225C40,
    },
}
