#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-08-10T23:08:12.943361200+00:00
# Build No: 14174
# Classes: 3330 | Enums: 553 | Offsets: 32 | Modules: 18
#

# Module: animationsystem.dll
class AnimationsystemDll: {
    AnimationSystemUtils_001 = 0x837ED0
    AnimationSystem_001 = 0x82FDF0
}
# Module: client.dll
class ClientDll: {
    ClientBugBugServic001_Client = 0x2098810
    ClientToolsInfo_001 = 0x20987E0
    EmptyWorldService001_Client = 0x20744E0
    GameClientExports001 = 0x2095480
    LegacyGameUI001 = 0x20A8D60
    Source2Client002 = 0x23A38D0
    Source2ClientConfig001 = 0x2310C30
    Source2ClientPrediction001 = 0x23A9020
    Source2ClientUI001 = 0x20A7280
}
# Module: engine2.dll
class Engine2Dll: {
    BenchmarkService001 = 0x615320
    BugBugService001 = 0x615420
    BugService001 = 0x8CDCD0
    ClientServerEngineLoopService_001 = 0x90F3D0
    ClientServerSharedHandleSystem001 = 0x90E9A0
    EngineGameUI001 = 0x612C70
    EngineServiceMgr001 = 0x90ECB0
    GameEventSystemClientV001 = 0x90EF90
    GameEventSystemServerV001 = 0x90F0C0
    GameResourceServiceClientV001 = 0x615460
    GameResourceServiceServerV001 = 0x6154C0
    GameUIService_001 = 0x8CE120
    HostStateMgr001 = 0x615CA0
    INETSUPPORT_001 = 0x60E960
    InputService_001 = 0x8CE410
    KeyValueCache001 = 0x615D50
    MapListService_001 = 0x90D280
    NetworkClientService_001 = 0x90D410
    NetworkP2PService_001 = 0x90D750
    NetworkServerService_001 = 0x90D900
    NetworkService_001 = 0x615630
    RenderService_001 = 0x90DB70
    ScreenshotService001 = 0x90DE30
    SimpleEngineLoopService_001 = 0x615DB0
    SoundService_001 = 0x615670
    Source2EngineToClient001 = 0x6125A0
    Source2EngineToClientStringTable001 = 0x612600
    Source2EngineToServer001 = 0x612678
    Source2EngineToServerStringTable001 = 0x6126A0
    SplitScreenService_001 = 0x615950
    StatsService_001 = 0x90E1F0
    ToolService_001 = 0x615B10
    VENGINE_GAMEUIFUNCS_VERSION005 = 0x612D00
    VProfService_001 = 0x615B50
}
# Module: filesystem_stdio.dll
class FilesystemStdioDll: {
    VAsyncFileSystem2_001 = 0x211600
    VFileSystem017 = 0x2113C0
}
# Module: host.dll
class HostDll: {
    DebugDrawQueueManager001 = 0x13E0A0
    GameModelInfo001 = 0x13E0E0
    GameSystem2HostHook = 0x13E120
    HostUtils001 = 0x14DB50
    PredictionDiffManager001 = 0x13E230
    SaveRestoreDataVersion001 = 0x13E360
    SinglePlayerSharedMemory001 = 0x13E390
    Source2Host001 = 0x13E400
}
# Module: imemanager.dll
class ImemanagerDll: {
    IMEManager001 = 0x36AA0
}
# Module: inputsystem.dll
class InputsystemDll: {
    InputStackSystemVersion001 = 0x43E90
    InputSystemVersion001 = 0x45BA0
}
# Module: localize.dll
class LocalizeDll: {
    Localize_001 = 0x58100
}
# Module: matchmaking.dll
class MatchmakingDll: {
    GameTypes001 = 0x1ADF80
    MATCHFRAMEWORK_001 = 0x1B5F00
}
# Module: materialsystem2.dll
class Materialsystem2Dll: {
    FontManager_001 = 0x15CBB0
    MaterialUtils_001 = 0x144F00
    PostProcessingSystem_001 = 0x144E30
    TextLayout_001 = 0x144E90
    VMaterialSystem2_001 = 0x15C800
}
# Module: meshsystem.dll
class MeshsystemDll: {
    MeshSystem001 = 0x16BDE0
}
# Module: navsystem.dll
class NavsystemDll: {
    NavSystem001 = 0x128C20
}
# Module: networksystem.dll
class NetworksystemDll: {
    FlattenedSerializersVersion001 = 0x26C810
    NetworkMessagesVersion001 = 0x294A30
    NetworkSystemVersion001 = 0x285F60
    SerializedEntitiesVersion001 = 0x286050
}
# Module: panorama.dll
class PanoramaDll: {
    PanoramaUIEngine001 = 0x50FD60
}
# Module: panorama_text_pango.dll
class PanoramaTextPangoDll: {
    PanoramaTextServices001 = 0x2B89D0
}
# Module: panoramauiclient.dll
class PanoramauiclientDll: {
    PanoramaUIClient001 = 0x295210
}
# Module: particles.dll
class ParticlesDll: {
    ParticleSystemMgr003 = 0x5FEAD0
}
# Module: pulse_system.dll
class PulseSystemDll: {
    IPulseSystem_001 = 0x219710
}
# Module: rendersystemdx11.dll
class Rendersystemdx11Dll: {
    RenderDeviceMgr001 = 0x42C550
    RenderUtils_001 = 0x42CE30
    VRenderDeviceMgrBackdoor001 = 0x42C5F0
}
# Module: resourcesystem.dll
class ResourcesystemDll: {
    ResourceSystem013 = 0x81680
}
# Module: scenefilecache.dll
class ScenefilecacheDll: {
    ResponseRulesCache001 = 0x113450
    SceneFileCache002 = 0x113578
}
# Module: scenesystem.dll
class ScenesystemDll: {
    RenderingPipelines_001 = 0x667F10
    SceneSystem_002 = 0x911530
    SceneUtils_001 = 0x668DD0
}
# Module: schemasystem.dll
class SchemasystemDll: {
    SchemaSystem_001 = 0x75730
}
# Module: server.dll
class ServerDll: {
    EmptyWorldService001_Server = 0x1C3DFA0
    EntitySubclassUtilsV001 = 0x1BEDB00
    NavGameTest001 = 0x1CB10E0
    ServerToolsInfo_001 = 0x1C779A8
    Source2GameClients001 = 0x1C76B90
    Source2GameDirector001 = 0x1DF8380
    Source2GameEntities001 = 0x1C77150
    Source2Server001 = 0x1C76FA0
    Source2ServerConfig001 = 0x1F61528
    customnavsystem001 = 0x1BD1F48
}
# Module: soundsystem.dll
class SoundsystemDll: {
    SoundBugBugService001_Client = 0x54BD80
    SoundOpSystem001 = 0x54BC60
    SoundOpSystemEdit001 = 0x54BB70
    SoundSystem001 = 0x54B5D0
    VMixEditTool001 = 0x594945F
}
# Module: steamaudio.dll
class SteamaudioDll: {
    SteamAudio001 = 0x260610
}
# Module: tier0.dll
class Tier0Dll: {
    TestScriptMgr001 = 0x399800
    VEngineCvar007 = 0x3A44F0
    VProcessUtils002 = 0x3997A0
    VStringTokenSystem001 = 0x3CB1F0
}
# Module: v8system.dll
class V8systemDll: {
    Source2V8System001 = 0x31770
}
# Module: vphysics2.dll
class Vphysics2Dll: {
    VPhysics2_Interface_001 = 0x428E90
}
# Module: vscript.dll
class VscriptDll: {
    VScriptManager010 = 0x13D430
}
# Module: worldrenderer.dll
class WorldrendererDll: {
    WorldRendererMgr001 = 0x231DA0
}
