//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-09-21T01:14:34.230008900+00:00
// Build No: 14181
// Classes: 3342 | Enums: 551 | Offsets: 32 | Modules: 18
//

#pragma once

#include <cstddef>
#include <cstdint>

namespace exitscam {
    namespace interfaces {
        // Module: animationsystem.dll
        namespace animationsystem_dll {
            constexpr std::ptrdiff_t AnimationSystemUtils_001 = 0x837F10;
            constexpr std::ptrdiff_t AnimationSystem_001 = 0x82FE30;
        }
        // Module: client.dll
        namespace client_dll {
            constexpr std::ptrdiff_t ClientBugBugServic001_Client = 0x20B9310;
            constexpr std::ptrdiff_t ClientToolsInfo_001 = 0x20B92E0;
            constexpr std::ptrdiff_t EmptyWorldService001_Client = 0x2095950;
            constexpr std::ptrdiff_t GameClientExports001 = 0x20B5F80;
            constexpr std::ptrdiff_t LegacyGameUI001 = 0x20C9870;
            constexpr std::ptrdiff_t Source2Client002 = 0x23C73C0;
            constexpr std::ptrdiff_t Source2ClientConfig001 = 0x2338290;
            constexpr std::ptrdiff_t Source2ClientPrediction001 = 0x23CCB10;
            constexpr std::ptrdiff_t Source2ClientUI001 = 0x20C7D80;
        }
        // Module: engine2.dll
        namespace engine2_dll {
            constexpr std::ptrdiff_t BenchmarkService001 = 0x616360;
            constexpr std::ptrdiff_t BugBugService001 = 0x616460;
            constexpr std::ptrdiff_t BugService001 = 0x8CEEC0;
            constexpr std::ptrdiff_t ClientServerEngineLoopService_001 = 0x9105C0;
            constexpr std::ptrdiff_t ClientServerSharedHandleSystem001 = 0x90FB90;
            constexpr std::ptrdiff_t EngineGameUI001 = 0x613C80;
            constexpr std::ptrdiff_t EngineServiceMgr001 = 0x90FEA0;
            constexpr std::ptrdiff_t GameEventSystemClientV001 = 0x910180;
            constexpr std::ptrdiff_t GameEventSystemServerV001 = 0x9102B0;
            constexpr std::ptrdiff_t GameResourceServiceClientV001 = 0x6164A0;
            constexpr std::ptrdiff_t GameResourceServiceServerV001 = 0x616500;
            constexpr std::ptrdiff_t GameUIService_001 = 0x8CF310;
            constexpr std::ptrdiff_t HostStateMgr001 = 0x616CE0;
            constexpr std::ptrdiff_t INETSUPPORT_001 = 0x60F970;
            constexpr std::ptrdiff_t InputService_001 = 0x8CF600;
            constexpr std::ptrdiff_t KeyValueCache001 = 0x616D90;
            constexpr std::ptrdiff_t MapListService_001 = 0x90E470;
            constexpr std::ptrdiff_t NetworkClientService_001 = 0x90E600;
            constexpr std::ptrdiff_t NetworkP2PService_001 = 0x90E940;
            constexpr std::ptrdiff_t NetworkServerService_001 = 0x90EAF0;
            constexpr std::ptrdiff_t NetworkService_001 = 0x616670;
            constexpr std::ptrdiff_t RenderService_001 = 0x90ED60;
            constexpr std::ptrdiff_t ScreenshotService001 = 0x90F020;
            constexpr std::ptrdiff_t SimpleEngineLoopService_001 = 0x616DF0;
            constexpr std::ptrdiff_t SoundService_001 = 0x6166B0;
            constexpr std::ptrdiff_t Source2EngineToClient001 = 0x6135B0;
            constexpr std::ptrdiff_t Source2EngineToClientStringTable001 = 0x613610;
            constexpr std::ptrdiff_t Source2EngineToServer001 = 0x613688;
            constexpr std::ptrdiff_t Source2EngineToServerStringTable001 = 0x6136B0;
            constexpr std::ptrdiff_t SplitScreenService_001 = 0x616990;
            constexpr std::ptrdiff_t StatsService_001 = 0x90F3E0;
            constexpr std::ptrdiff_t ToolService_001 = 0x616B50;
            constexpr std::ptrdiff_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x613D10;
            constexpr std::ptrdiff_t VProfService_001 = 0x616B90;
        }
        // Module: filesystem_stdio.dll
        namespace filesystem_stdio_dll {
            constexpr std::ptrdiff_t VAsyncFileSystem2_001 = 0x213600;
            constexpr std::ptrdiff_t VFileSystem017 = 0x2133C0;
        }
        // Module: host.dll
        namespace host_dll {
            constexpr std::ptrdiff_t DebugDrawQueueManager001 = 0x13E0A0;
            constexpr std::ptrdiff_t GameModelInfo001 = 0x13E0E0;
            constexpr std::ptrdiff_t GameSystem2HostHook = 0x13E120;
            constexpr std::ptrdiff_t HostUtils001 = 0x14DB50;
            constexpr std::ptrdiff_t PredictionDiffManager001 = 0x13E230;
            constexpr std::ptrdiff_t SaveRestoreDataVersion001 = 0x13E360;
            constexpr std::ptrdiff_t SinglePlayerSharedMemory001 = 0x13E390;
            constexpr std::ptrdiff_t Source2Host001 = 0x13E400;
        }
        // Module: imemanager.dll
        namespace imemanager_dll {
            constexpr std::ptrdiff_t IMEManager001 = 0x36AA0;
        }
        // Module: inputsystem.dll
        namespace inputsystem_dll {
            constexpr std::ptrdiff_t InputStackSystemVersion001 = 0x43E90;
            constexpr std::ptrdiff_t InputSystemVersion001 = 0x45BA0;
        }
        // Module: localize.dll
        namespace localize_dll {
            constexpr std::ptrdiff_t Localize_001 = 0x58100;
        }
        // Module: matchmaking.dll
        namespace matchmaking_dll {
            constexpr std::ptrdiff_t GameTypes001 = 0x1ADF80;
            constexpr std::ptrdiff_t MATCHFRAMEWORK_001 = 0x1B6020;
        }
        // Module: materialsystem2.dll
        namespace materialsystem2_dll {
            constexpr std::ptrdiff_t FontManager_001 = 0x15CBB0;
            constexpr std::ptrdiff_t MaterialUtils_001 = 0x144F00;
            constexpr std::ptrdiff_t PostProcessingSystem_001 = 0x144E30;
            constexpr std::ptrdiff_t TextLayout_001 = 0x144E90;
            constexpr std::ptrdiff_t VMaterialSystem2_001 = 0x15C800;
        }
        // Module: meshsystem.dll
        namespace meshsystem_dll {
            constexpr std::ptrdiff_t MeshSystem001 = 0x16BDE0;
        }
        // Module: navsystem.dll
        namespace navsystem_dll {
            constexpr std::ptrdiff_t NavSystem001 = 0x128C20;
        }
        // Module: networksystem.dll
        namespace networksystem_dll {
            constexpr std::ptrdiff_t FlattenedSerializersVersion001 = 0x26C840;
            constexpr std::ptrdiff_t NetworkMessagesVersion001 = 0x298AC0;
            constexpr std::ptrdiff_t NetworkSystemVersion001 = 0x285F90;
            constexpr std::ptrdiff_t SerializedEntitiesVersion001 = 0x286080;
        }
        // Module: panorama.dll
        namespace panorama_dll {
            constexpr std::ptrdiff_t PanoramaUIEngine001 = 0x50FD60;
        }
        // Module: panorama_text_pango.dll
        namespace panorama_text_pango_dll {
            constexpr std::ptrdiff_t PanoramaTextServices001 = 0x2B89D0;
        }
        // Module: panoramauiclient.dll
        namespace panoramauiclient_dll {
            constexpr std::ptrdiff_t PanoramaUIClient001 = 0x295210;
        }
        // Module: particles.dll
        namespace particles_dll {
            constexpr std::ptrdiff_t ParticleSystemMgr003 = 0x5FEAC0;
        }
        // Module: pulse_system.dll
        namespace pulse_system_dll {
            constexpr std::ptrdiff_t IPulseSystem_001 = 0x219750;
        }
        // Module: rendersystemdx11.dll
        namespace rendersystemdx11_dll {
            constexpr std::ptrdiff_t RenderDeviceMgr001 = 0x42C550;
            constexpr std::ptrdiff_t RenderUtils_001 = 0x42CE30;
            constexpr std::ptrdiff_t VRenderDeviceMgrBackdoor001 = 0x42C5F0;
        }
        // Module: resourcesystem.dll
        namespace resourcesystem_dll {
            constexpr std::ptrdiff_t ResourceSystem013 = 0x81680;
        }
        // Module: scenefilecache.dll
        namespace scenefilecache_dll {
            constexpr std::ptrdiff_t ResponseRulesCache001 = 0x113450;
            constexpr std::ptrdiff_t SceneFileCache002 = 0x113578;
        }
        // Module: scenesystem.dll
        namespace scenesystem_dll {
            constexpr std::ptrdiff_t RenderingPipelines_001 = 0x667F10;
            constexpr std::ptrdiff_t SceneSystem_002 = 0x911530;
            constexpr std::ptrdiff_t SceneUtils_001 = 0x668DD0;
        }
        // Module: schemasystem.dll
        namespace schemasystem_dll {
            constexpr std::ptrdiff_t SchemaSystem_001 = 0x75730;
        }
        // Module: server.dll
        namespace server_dll {
            constexpr std::ptrdiff_t EmptyWorldService001_Server = 0x1C70470;
            constexpr std::ptrdiff_t EntitySubclassUtilsV001 = 0x1C1EAE0;
            constexpr std::ptrdiff_t NavGameTest001 = 0x1CE2C60;
            constexpr std::ptrdiff_t ServerToolsInfo_001 = 0x1CA9538;
            constexpr std::ptrdiff_t Source2GameClients001 = 0x1CA8720;
            constexpr std::ptrdiff_t Source2GameDirector001 = 0x1E2ACE0;
            constexpr std::ptrdiff_t Source2GameEntities001 = 0x1CA8CE0;
            constexpr std::ptrdiff_t Source2Server001 = 0x1CA8B30;
            constexpr std::ptrdiff_t Source2ServerConfig001 = 0x1F99D98;
            constexpr std::ptrdiff_t customnavsystem001 = 0x1C02F28;
        }
        // Module: soundsystem.dll
        namespace soundsystem_dll {
            constexpr std::ptrdiff_t SoundBugBugService001_Client = 0x54BD80;
            constexpr std::ptrdiff_t SoundOpSystem001 = 0x54BC60;
            constexpr std::ptrdiff_t SoundOpSystemEdit001 = 0x54BB70;
            constexpr std::ptrdiff_t SoundSystem001 = 0x54B5D0;
            constexpr std::ptrdiff_t VMixEditTool001 = 0x594945F;
        }
        // Module: steamaudio.dll
        namespace steamaudio_dll {
            constexpr std::ptrdiff_t SteamAudio001 = 0x260610;
        }
        // Module: tier0.dll
        namespace tier0_dll {
            constexpr std::ptrdiff_t TestScriptMgr001 = 0x39A800;
            constexpr std::ptrdiff_t VEngineCvar007 = 0x3A54F0;
            constexpr std::ptrdiff_t VProcessUtils002 = 0x39A7A0;
            constexpr std::ptrdiff_t VStringTokenSystem001 = 0x3CC1F0;
        }
        // Module: v8system.dll
        namespace v8system_dll {
            constexpr std::ptrdiff_t Source2V8System001 = 0x31770;
        }
        // Module: vphysics2.dll
        namespace vphysics2_dll {
            constexpr std::ptrdiff_t VPhysics2_Interface_001 = 0x428E90;
        }
        // Module: vscript.dll
        namespace vscript_dll {
            constexpr std::ptrdiff_t VScriptManager010 = 0x13D430;
        }
        // Module: worldrenderer.dll
        namespace worldrenderer_dll {
            constexpr std::ptrdiff_t WorldRendererMgr001 = 0x231DA0;
        }
    }
}
