#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-04-21T00:48:31.099236600+00:00
# Build No: 14151
# Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
#

# Module: materialsystem2.dll
class Materialsystem2Dll: {
    class VertJustification_e: {
        VERT_JUSTIFICATION_TOP = 0x0
        VERT_JUSTIFICATION_CENTER = 0x1
        VERT_JUSTIFICATION_BOTTOM = 0x2
        VERT_JUSTIFICATION_NONE = 0x3
    }
    class LayoutPositionType_e: {
        LAYOUTPOSITIONTYPE_VIEWPORT_RELATIVE = 0x0
        LAYOUTPOSITIONTYPE_FRACTIONAL = 0x1
        LAYOUTPOSITIONTYPE_NONE = 0x2
    }
    class ViewFadeMode_t: {
        VIEW_FADE_CONSTANT_COLOR = 0x0
        VIEW_FADE_MODULATE = 0x1
        VIEW_FADE_MOD2X = 0x2
    }
    class BloomBlendMode_t: {
        BLOOM_BLEND_ADD = 0x0
        BLOOM_BLEND_SCREEN = 0x1
        BLOOM_BLEND_BLUR = 0x2
    }
    class HorizJustification_e: {
        HORIZ_JUSTIFICATION_LEFT = 0x0
        HORIZ_JUSTIFICATION_CENTER = 0x1
        HORIZ_JUSTIFICATION_RIGHT = 0x2
        HORIZ_JUSTIFICATION_NONE = 0x3
    }
    class MaterialParam_t: {
         = 0x0 # 
    }
    class MaterialParamVector_t: {
        pass
    }
    class MaterialParamString_t: {
        pass
    }
    class PostProcessingResource_t: {
         = 0x0 # 
    }
    class MaterialParamInt_t: {
        pass
    }
    class PostProcessingVignetteParameters_t: {
         = 0x0 # 
    }
    class PostProcessingLocalContrastParameters_t: {
         = 0x0 # 
    }
    class PostProcessingTonemapParameters_t: {
         = 0x0 # 
    }
    class PostProcessingFogScatteringParameters_t: {
         = 0x0 # 
    }
    class MaterialParamBuffer_t: {
        pass
    }
    class MaterialResourceData_t: {
         = 0x0 # 
    }
    class PostProcessingBloomParameters_t: {
         = 0x0 # 
    }
    class MaterialParamFloat_t: {
        pass
    }
    class MaterialParamTexture_t: {
        pass
    }
}
