//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-04-21T00:48:31.099236600+00:00
// Build No: 14151
// Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
//

namespace ExitScam.Schemas {
    // Module: materialsystem2.dll
    // Class count: 14
    // Enum count: 5
    public static class Materialsystem2Dll {
        // Alignment: 4
        // Member count: 4
        public enum VertJustification_e : uint {
            VERT_JUSTIFICATION_TOP = 0x0,
            VERT_JUSTIFICATION_CENTER = 0x1,
            VERT_JUSTIFICATION_BOTTOM = 0x2,
            VERT_JUSTIFICATION_NONE = 0x3
        }
        // Alignment: 4
        // Member count: 3
        public enum LayoutPositionType_e : uint {
            LAYOUTPOSITIONTYPE_VIEWPORT_RELATIVE = 0x0,
            LAYOUTPOSITIONTYPE_FRACTIONAL = 0x1,
            LAYOUTPOSITIONTYPE_NONE = 0x2
        }
        // Alignment: 4
        // Member count: 3
        public enum ViewFadeMode_t : uint {
            VIEW_FADE_CONSTANT_COLOR = 0x0,
            VIEW_FADE_MODULATE = 0x1,
            VIEW_FADE_MOD2X = 0x2
        }
        // Alignment: 4
        // Member count: 3
        public enum BloomBlendMode_t : uint {
            BLOOM_BLEND_ADD = 0x0,
            BLOOM_BLEND_SCREEN = 0x1,
            BLOOM_BLEND_BLUR = 0x2
        }
        // Alignment: 4
        // Member count: 4
        public enum HorizJustification_e : uint {
            HORIZ_JUSTIFICATION_LEFT = 0x0,
            HORIZ_JUSTIFICATION_CENTER = 0x1,
            HORIZ_JUSTIFICATION_RIGHT = 0x2,
            HORIZ_JUSTIFICATION_NONE = 0x3
        }
        // Parent: None
        // Field count: 1
        public static class MaterialParam_t {
            public const nint  = 0x0; // 
        }
        // Parent: materialsystem2
        // Field count: 0
        public static class MaterialParamVector_t {
        }
        // Parent: materialsystem2
        // Field count: 0
        public static class MaterialParamString_t {
        }
        // Parent: None
        // Field count: 1
        public static class PostProcessingResource_t {
            public const nint  = 0x0; // 
        }
        // Parent: None
        // Field count: 0
        public static class MaterialParamInt_t {
        }
        // Parent: None
        // Field count: 1
        public static class PostProcessingVignetteParameters_t {
            public const nint  = 0x0; // 
        }
        // Parent: None
        // Field count: 1
        public static class PostProcessingLocalContrastParameters_t {
            public const nint  = 0x0; // 
        }
        // Parent: None
        // Field count: 1
        public static class PostProcessingTonemapParameters_t {
            public const nint  = 0x0; // 
        }
        // Parent: None
        // Field count: 1
        public static class PostProcessingFogScatteringParameters_t {
            public const nint  = 0x0; // 
        }
        // Parent: xL_z__
        // Field count: 0
        public static class MaterialParamBuffer_t {
        }
        // Parent: None
        // Field count: 1
        public static class MaterialResourceData_t {
            public const nint  = 0x0; // 
        }
        // Parent: None
        // Field count: 1
        public static class PostProcessingBloomParameters_t {
            public const nint  = 0x0; // 
        }
        // Parent: None
        // Field count: 0
        public static class MaterialParamFloat_t {
        }
        // Parent: None
        // Field count: 0
        public static class MaterialParamTexture_t {
        }
    }
}
