//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-10-08T23:59:47.471202400+00:00
// Build No: 14190
// Classes: 3301 | Enums: 568 | Offsets: 31 | Modules: 18
//

namespace ExitScam.Schemas {
    // Module: networksystem.dll
    // Class count: 1
    // Enum count: 0
    public static class NetworksystemDll {
        // Parent: None
        // Field count: 1
        public static class ChangeAccessorFieldPathIndex_t {
            public const nint m_Value = 0x0; // int32
        }
    }
}
