--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-05-19T10:11:29.994787500+00:00
-- Build No: 14162
-- Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
--

return {
    client_dll = {
        dwCSGOInput = 0x237B5B0,
        dwEntityList = 0x250C5B0,
        dwGameEntitySystem = 0x250C5B0,
        dwGameEntitySystem_highestEntityIndex = 0x2090,
        dwGameRules = 0x1A21D28,
        dwGlobalVars = 0x2085788,
        dwGlowManager = 0x2363580,
        dwLocalPlayerController = 0x2345D50,
        dwLocalPlayerPawn = 0x2090880,
        dwPlantedC4 = 0x2374278,
        dwPrediction = 0x2090790,
        dwSensitivity = 0x2364098,
        dwSensitivity_sensitivity = 0x58,
        dwViewAngles = 0x237BC38,
        dwViewMatrix = 0x236C2F0,
        dwViewRender = 0x236B4F8,
        dwWeaponC4 = 0x22E4518,
    },
    engine2_dll = {
        dwBuildNumber = 0x60CC74,
        dwNetworkGameClient = 0x90A1A0,
        dwNetworkGameClient_clientTickCount = 0x378,
        dwNetworkGameClient_deltaTick = 0x24C,
        dwNetworkGameClient_isBackgroundMap = 0x2C141F,
        dwNetworkGameClient_localPlayer = 0xF8,
        dwNetworkGameClient_maxClients = 0x240,
        dwNetworkGameClient_serverTickCount = 0x24C,
        dwNetworkGameClient_signOnState = 0x230,
        dwWindowHeight = 0x90E5C4,
        dwWindowWidth = 0x90E5C0,
    },
    inputsystem_dll = {
        dwInputSystem = 0x42B50,
    },
    matchmaking_dll = {
        dwGameTypes = 0x1DF0B0,
    },
    soundsystem_dll = {
        dwSoundSystem = 0x512360,
        dwSoundSystem_engineViewData = 0x7C,
    },
}
