#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-08-20T00:07:26.459022500+00:00
# Build No: 14176
# Classes: 3330 | Enums: 549 | Offsets: 32 | Modules: 18
#

# Module: client.dll
class ClientDll: {
    dwCSGOInput = 0x23BFB20
    dwEntityList = 0x2555050
    dwGameEntitySystem = 0x2555050
    dwGameEntitySystem_highestEntityIndex = 0x2090
    dwGameRules = 0x1A56348
    dwGlobalVars = 0x2095D48
    dwGlowManager = 0x23A6908
    dwLocalPlayerController = 0x2384DB0
    dwLocalPlayerPawn = 0x23AA118
    dwPlantedC4 = 0x2374898
    dwPrediction = 0x23AA020
    dwSensitivity = 0x23A7428
    dwSensitivity_sensitivity = 0x58
    dwViewAngles = 0x23C01A8
    dwViewMatrix = 0x23AF550
    dwViewRender = 0x23AF5A8
    dwWeaponC4 = 0x2322DA0
}
# Module: engine2.dll
class Engine2Dll: {
    dwBuildNumber = 0x60F594
    dwNetworkGameClient = 0x90D4B0
    dwNetworkGameClient_clientTickCount = 0x378
    dwNetworkGameClient_deltaTick = 0x24C
    dwNetworkGameClient_isBackgroundMap = 0x2C141F
    dwNetworkGameClient_localPlayer = 0xF8
    dwNetworkGameClient_maxClients = 0x240
    dwNetworkGameClient_serverTickCount = 0x24C
    dwNetworkGameClient_signOnState = 0x230
    dwWindowHeight = 0x9118DC
    dwWindowWidth = 0x9118D8
}
# Module: inputsystem.dll
class InputsystemDll: {
    dwInputSystem = 0x45BA0
}
# Module: matchmaking.dll
class MatchmakingDll: {
    dwGameTypes = 0x1ADF80
}
# Module: soundsystem.dll
class SoundsystemDll: {
    dwSoundSystem = 0x54B5D0
    dwSoundSystem_engineViewData = 0x7C
}
