--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-04-28T22:40:14.071312+00:00
-- Build No: 14156
-- Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
--

return {
    client_dll = {
        dwCSGOInput = 0x233DC80,
        dwEntityList = 0x24CEC60,
        dwGameEntitySystem = 0x24CEC60,
        dwGameEntitySystem_highestEntityIndex = 0x2090,
        dwGameRules = 0x19EEA50,
        dwGlobalVars = 0x20495A0,
        dwGlowManager = 0x2325C30,
        dwLocalPlayerController = 0x23084C0,
        dwLocalPlayerPawn = 0x20546A0,
        dwPlantedC4 = 0x2336948,
        dwPrediction = 0x20545B0,
        dwSensitivity = 0x2326748,
        dwSensitivity_sensitivity = 0x58,
        dwViewAngles = 0x233E308,
        dwViewMatrix = 0x232E9C0,
        dwViewRender = 0x232DBB8,
        dwWeaponC4 = 0x22A6C68,
    },
    engine2_dll = {
        dwBuildNumber = 0x60CC74,
        dwNetworkGameClient = 0x90A0C0,
        dwNetworkGameClient_clientTickCount = 0x378,
        dwNetworkGameClient_deltaTick = 0x24C,
        dwNetworkGameClient_isBackgroundMap = 0x2C141F,
        dwNetworkGameClient_localPlayer = 0xF8,
        dwNetworkGameClient_maxClients = 0x240,
        dwNetworkGameClient_serverTickCount = 0x24C,
        dwNetworkGameClient_signOnState = 0x230,
        dwWindowHeight = 0x90E4EC,
        dwWindowWidth = 0x90E4E8,
    },
    inputsystem_dll = {
        dwInputSystem = 0x42B50,
    },
    matchmaking_dll = {
        dwGameTypes = 0x1B0F80,
    },
    soundsystem_dll = {
        dwSoundSystem = 0x512360,
        dwSoundSystem_engineViewData = 0x7C,
    },
}
