--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-05-08T04:51:02.030756300+00:00
-- Build No: 14160
-- Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
--

return {
    client_dll = {
        dwCSGOInput = 0x233FC00,
        dwEntityList = 0x24D0DC0,
        dwGameEntitySystem = 0x24D0DC0,
        dwGameEntitySystem_highestEntityIndex = 0x2090,
        dwGameRules = 0x19F0A60,
        dwGlobalVars = 0x204B5D8,
        dwGlowManager = 0x2327D40,
        dwLocalPlayerController = 0x230A4F0,
        dwLocalPlayerPawn = 0x2056700,
        dwPlantedC4 = 0x2338A68,
        dwPrediction = 0x2056610,
        dwSensitivity = 0x2328858,
        dwSensitivity_sensitivity = 0x58,
        dwViewAngles = 0x2340288,
        dwViewMatrix = 0x2330AE0,
        dwViewRender = 0x232FCD0,
        dwWeaponC4 = 0x22A8E38,
    },
    engine2_dll = {
        dwBuildNumber = 0x60BC74,
        dwNetworkGameClient = 0x9090C0,
        dwNetworkGameClient_clientTickCount = 0x378,
        dwNetworkGameClient_deltaTick = 0x24C,
        dwNetworkGameClient_isBackgroundMap = 0x2C141F,
        dwNetworkGameClient_localPlayer = 0xF8,
        dwNetworkGameClient_maxClients = 0x240,
        dwNetworkGameClient_serverTickCount = 0x24C,
        dwNetworkGameClient_signOnState = 0x230,
        dwWindowHeight = 0x90D4EC,
        dwWindowWidth = 0x90D4E8,
    },
    inputsystem_dll = {
        dwInputSystem = 0x42B50,
    },
    matchmaking_dll = {
        dwGameTypes = 0x1B0F80,
    },
    soundsystem_dll = {
        dwSoundSystem = 0x512360,
        dwSoundSystem_engineViewData = 0x7C,
    },
}
