//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-07-21T03:49:23.368973400+00:00
// Build No: 14172
// Classes: 3330 | Enums: 549 | Offsets: 32 | Modules: 18
//

export const Offsets = {
    client_dll : {
        dwCSGOInput : 0x23BA790,
        dwEntityList : 0x254FE70,
        dwGameEntitySystem : 0x254FE70,
        dwGameEntitySystem_highestEntityIndex : 0x2090,
        dwGameRules : 0x1A525C0,
        dwGlobalVars : 0x2090D60,
        dwGlowManager : 0x23A1708,
        dwLocalPlayerController : 0x237FB70,
        dwLocalPlayerPawn : 0x23A5238,
        dwPlantedC4 : 0x236F658,
        dwPrediction : 0x23A5140,
        dwSensitivity : 0x23A2228,
        dwSensitivity_sensitivity : 0x58,
        dwViewAngles : 0x23BAE18,
        dwViewMatrix : 0x23AA340,
        dwViewRender : 0x23AA398,
        dwWeaponC4 : 0x231DB10,
    },
    engine2_dll : {
        dwBuildNumber : 0x60F594,
        dwNetworkGameClient : 0x90D4B0,
        dwNetworkGameClient_clientTickCount : 0x378,
        dwNetworkGameClient_deltaTick : 0x24C,
        dwNetworkGameClient_isBackgroundMap : 0x2C141F,
        dwNetworkGameClient_localPlayer : 0xF8,
        dwNetworkGameClient_maxClients : 0x240,
        dwNetworkGameClient_serverTickCount : 0x24C,
        dwNetworkGameClient_signOnState : 0x230,
        dwWindowHeight : 0x9118D4,
        dwWindowWidth : 0x9118D0,
    },
    inputsystem_dll : {
        dwInputSystem : 0x45BA0,
    },
    matchmaking_dll : {
        dwGameTypes : 0x1ADF80,
    },
    soundsystem_dll : {
        dwSoundSystem : 0x54B5D0,
        dwSoundSystem_engineViewData : 0x7C,
    },
} as const;

