//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-10-03T17:12:07.368262500+00:00
// Build No: 14188
// Classes: 3301 | Enums: 569 | Offsets: 31 | Modules: 18
//

namespace ExitScam.Offsets {
    // Module: client.dll
    public static class ClientDll {
        public const nint dwCSGOInput = 0x2576150;
        public const nint dwEntityList = 0x2715818;
        public const nint dwGameEntitySystem = 0x2715818;
        public const nint dwGameEntitySystem_highestEntityIndex = 0x2120;
        public const nint dwGameRules = 0x1BB0E90;
        public const nint dwGlobalVars = 0x222BE98;
        public const nint dwGlowManager = 0x255CE60;
        public const nint dwLocalPlayerController = 0x2538008;
        public const nint dwLocalPlayerPawn = 0x2560698;
        public const nint dwPlantedC4 = 0x24C88D0;
        public const nint dwPrediction = 0x25605A0;
        public const nint dwSensitivity = 0x255D998;
        public const nint dwSensitivity_sensitivity = 0x58;
        public const nint dwViewAngles = 0x25767D8;
        public const nint dwViewMatrix = 0x2566910;
        public const nint dwViewRender = 0x2565D20;
        public const nint dwWeaponC4 = 0x24C4A90;
    }
    // Module: engine2.dll
    public static class Engine2Dll {
        public const nint dwBuildNumber = 0x61CFE8;
        public const nint dwNetworkGameClient = 0x91AFC0;
        public const nint dwNetworkGameClient_clientTickCount = 0x398;
        public const nint dwNetworkGameClient_deltaTick = 0x24C;
        public const nint dwNetworkGameClient_localPlayer = 0xF8;
        public const nint dwNetworkGameClient_maxClients = 0x240;
        public const nint dwNetworkGameClient_serverTickCount = 0x24C;
        public const nint dwNetworkGameClient_signOnState = 0x230;
        public const nint dwWindowHeight = 0x91F334;
        public const nint dwWindowWidth = 0x91F330;
    }
    // Module: inputsystem.dll
    public static class InputsystemDll {
        public const nint dwInputSystem = 0x46BC0;
    }
    // Module: matchmaking.dll
    public static class MatchmakingDll {
        public const nint dwGameTypes = 0x1B0FD0;
    }
    // Module: soundsystem.dll
    public static class SoundsystemDll {
        public const nint dwSoundSystem = 0x535350;
        public const nint dwSoundSystem_engineViewData = 0x6C;
    }
}
