//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-07-01T08:23:32.583926300+00:00
// Build No: 14166
// Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
//

export const Offsets = {
    client_dll : {
        dwCSGOInput : 0x23560C0,
        dwEntityList : 0x24E7680,
        dwGameEntitySystem : 0x24E7680,
        dwGameEntitySystem_highestEntityIndex : 0x2090,
        dwGameRules : 0x1A02BC0,
        dwGlobalVars : 0x20616D0,
        dwGlowManager : 0x233DDE0,
        dwLocalPlayerController : 0x2320570,
        dwLocalPlayerPawn : 0x2341528,
        dwPlantedC4 : 0x234FE28,
        dwPrediction : 0x2341430,
        dwSensitivity : 0x233E8F8,
        dwSensitivity_sensitivity : 0x58,
        dwViewAngles : 0x2356748,
        dwViewMatrix : 0x23469C0,
        dwViewRender : 0x2346D70,
        dwWeaponC4 : 0x22BED18,
    },
    engine2_dll : {
        dwBuildNumber : 0x60CC74,
        dwNetworkGameClient : 0x90A1A0,
        dwNetworkGameClient_clientTickCount : 0x378,
        dwNetworkGameClient_deltaTick : 0x24C,
        dwNetworkGameClient_isBackgroundMap : 0x2C141F,
        dwNetworkGameClient_localPlayer : 0xF8,
        dwNetworkGameClient_maxClients : 0x240,
        dwNetworkGameClient_serverTickCount : 0x24C,
        dwNetworkGameClient_signOnState : 0x230,
        dwWindowHeight : 0x90E5C4,
        dwWindowWidth : 0x90E5C0,
    },
    inputsystem_dll : {
        dwInputSystem : 0x42B50,
    },
    matchmaking_dll : {
        dwGameTypes : 0x1B0F80,
    },
    soundsystem_dll : {
        dwSoundSystem : 0x512360,
        dwSoundSystem_engineViewData : 0x7C,
    },
} as const;

