#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-09-23T23:12:22.196847900+00:00
# Build No: 14183
# Classes: 3301 | Enums: 570 | Offsets: 31 | Modules: 18
#

# Module: client.dll
class ClientDll: {
    dwCSGOInput = 0x2571A90
    dwEntityList = 0x2711048
    dwGameEntitySystem = 0x2711048
    dwGameEntitySystem_highestEntityIndex = 0x2120
    dwGameRules = 0x1BADA70
    dwGlobalVars = 0x2227F08
    dwGlowManager = 0x25587B0
    dwLocalPlayerController = 0x25334D8
    dwLocalPlayerPawn = 0x255C5A8
    dwPlantedC4 = 0x24C4E20
    dwPrediction = 0x255C4B0
    dwSensitivity = 0x25592E8
    dwSensitivity_sensitivity = 0x58
    dwViewAngles = 0x2572118
    dwViewMatrix = 0x25618F0
    dwViewRender = 0x25621B0
    dwWeaponC4 = 0x24C0530
}
# Module: engine2.dll
class Engine2Dll: {
    dwBuildNumber = 0x61C1EC
    dwNetworkGameClient = 0x91A150
    dwNetworkGameClient_clientTickCount = 0x398
    dwNetworkGameClient_deltaTick = 0x24C
    dwNetworkGameClient_localPlayer = 0xF8
    dwNetworkGameClient_maxClients = 0x240
    dwNetworkGameClient_serverTickCount = 0x24C
    dwNetworkGameClient_signOnState = 0x230
    dwWindowHeight = 0x91E4DC
    dwWindowWidth = 0x91E4D8
}
# Module: inputsystem.dll
class InputsystemDll: {
    dwInputSystem = 0x46BC0
}
# Module: matchmaking.dll
class MatchmakingDll: {
    dwGameTypes = 0x1B0FD0
}
# Module: soundsystem.dll
class SoundsystemDll: {
    dwSoundSystem = 0x535340
    dwSoundSystem_engineViewData = 0x6C
}
