#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-05-29T03:28:29.280905+00:00
# Build No: 14165
# Classes: 3224 | Enums: 480 | Offsets: 32 | Modules: 18
#

# Module: client.dll
class ClientDll: {
    dwCSGOInput = 0x2354230
    dwEntityList = 0x24E5590
    dwGameEntitySystem = 0x24E5590
    dwGameEntitySystem_highestEntityIndex = 0x2090
    dwGameRules = 0x1A00BA8
    dwGlobalVars = 0x205F6D0
    dwGlowManager = 0x233BF50
    dwLocalPlayerController = 0x231E700
    dwLocalPlayerPawn = 0x233F698
    dwPlantedC4 = 0x234DF88
    dwPrediction = 0x233F5A0
    dwSensitivity = 0x233CA68
    dwSensitivity_sensitivity = 0x58
    dwViewAngles = 0x23548B8
    dwViewMatrix = 0x2344B30
    dwViewRender = 0x2344ED8
    dwWeaponC4 = 0x22BCD00
}
# Module: engine2.dll
class Engine2Dll: {
    dwBuildNumber = 0x60CC74
    dwNetworkGameClient = 0x90A1A0
    dwNetworkGameClient_clientTickCount = 0x378
    dwNetworkGameClient_deltaTick = 0x24C
    dwNetworkGameClient_isBackgroundMap = 0x2C141F
    dwNetworkGameClient_localPlayer = 0xF8
    dwNetworkGameClient_maxClients = 0x240
    dwNetworkGameClient_serverTickCount = 0x24C
    dwNetworkGameClient_signOnState = 0x230
    dwWindowHeight = 0x90E5C4
    dwWindowWidth = 0x90E5C0
}
# Module: inputsystem.dll
class InputsystemDll: {
    dwInputSystem = 0x42B50
}
# Module: matchmaking.dll
class MatchmakingDll: {
    dwGameTypes = 0x1B0F80
}
# Module: soundsystem.dll
class SoundsystemDll: {
    dwSoundSystem = 0x512360
    dwSoundSystem_engineViewData = 0x7C
}
