--   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
--   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
--   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
--   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
--   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
--   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
-- 
-- Generated by ExitScam Dumper
-- 
-- Timestamp: 2026-04-21T00:48:31.099236600+00:00
-- Build No: 14151
-- Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
--

return {
    particles_dll = {
        PulseBestOutflowRules_t = {
            SORT_BY_NUMBER_OF_VALID_CRITERIA = 0x0,
            SORT_BY_OUTFLOW_INDEX = 0x1,
        },
        PulseCursorCancelPriority_t = {
            None = 0x0,
            CancelOnSucceeded = 0x1,
            SoftCancel = 0x2,
            HardCancel = 0x3,
        },
        PulseMethodCallMode_t = {
            SYNC_WAIT_FOR_COMPLETION = 0x0,
            ASYNC_FIRE_AND_FORGET = 0x1,
        },
        Detail2Combo_t = {
            DETAIL_2_COMBO_UNINITIALIZED = -1,
            DETAIL_2_COMBO_OFF = 0x0,
            DETAIL_2_COMBO_ADD = 0x1,
            DETAIL_2_COMBO_ADD_SELF_ILLUM = 0x2,
            DETAIL_2_COMBO_MOD2X = 0x3,
            DETAIL_2_COMBO_MUL = 0x4,
            DETAIL_2_COMBO_CROSSFADE = 0x5,
        },
        MissingParentInheritBehavior_t = {
            MISSING_PARENT_DO_NOTHING = -1,
            MISSING_PARENT_KILL = 0x0,
            MISSING_PARENT_FIND_NEW = 0x1,
            MISSING_PARENT_SAME_INDEX = 0x2,
        },
        ParticleTraceMissBehavior_t = {
            PARTICLE_TRACE_MISS_BEHAVIOR_NONE = 0x0,
            PARTICLE_TRACE_MISS_BEHAVIOR_KILL = 0x1,
            PARTICLE_TRACE_MISS_BEHAVIOR_TRACE_END = 0x2,
        },
        PFuncVisualizationType_t = {
            PFUNC_VISUALIZATION_SPHERE_WIREFRAME = 0x0,
            PFUNC_VISUALIZATION_SPHERE_SOLID = 0x1,
            PFUNC_VISUALIZATION_BOX = 0x2,
            PFUNC_VISUALIZATION_RING = 0x3,
            PFUNC_VISUALIZATION_PLANE = 0x4,
            PFUNC_VISUALIZATION_LINE = 0x5,
            PFUNC_VISUALIZATION_CYLINDER = 0x6,
        },
        ParticleVRHandChoiceList_t = {
            PARTICLE_VRHAND_LEFT = 0x0,
            PARTICLE_VRHAND_RIGHT = 0x1,
            PARTICLE_VRHAND_CP = 0x2,
            PARTICLE_VRHAND_CP_OBJECT = 0x3,
        },
        ParticleReplicationMode_t = {
            PARTICLE_REPLICATIONMODE_NONE = 0x0,
            PARTICLE_REPLICATIONMODE_REPLICATE_FOR_EACH_PARENT_PARTICLE = 0x1,
        },
        ParticleEntityPos_t = {
            PARTICLE_ABS_ORIGIN = 0x0,
            PARTICLE_WORLDSPACE_CENTER = 0x1,
            PARTICLE_EYES = 0x2,
        },
        ParticleFanType_t = {
            PARTICLE_FAN_TYPE_FAN = 0x0,
            PARTICLE_FAN_TYPE_ROTOR_WASH = 0x1,
            PARTICLE_FAN_TYPE_RADIAL = 0x2,
        },
        PetGroundType_t = {
            PET_GROUND_NONE = 0x0,
            PET_GROUND_GRID = 0x1,
            PET_GROUND_PLANE = 0x2,
        },
        InheritableBoolType_t = {
            INHERITABLE_BOOL_INHERIT = 0x0,
            INHERITABLE_BOOL_FALSE = 0x1,
            INHERITABLE_BOOL_TRUE = 0x2,
        },
        ParticlePostProcessPriorityGroup_t = {
            PARTICLE_POST_PROCESS_PRIORITY_LEVEL_VOLUME = 0x0,
            PARTICLE_POST_PROCESS_PRIORITY_LEVEL_OVERRIDE = 0x1,
            PARTICLE_POST_PROCESS_PRIORITY_GAMEPLAY_EFFECT = 0x2,
            PARTICLE_POST_PROCESS_PRIORITY_GAMEPLAY_STATE_LOW = 0x3,
            PARTICLE_POST_PROCESS_PRIORITY_GAMEPLAY_STATE_HIGH = 0x4,
            PARTICLE_POST_PROCESS_PRIORITY_GLOBAL_UI = 0x5,
        },
        ParticleCollisionGroup_t = {
            PARTICLE_COLLISION_GROUP_DEFAULT = 0x4,
            PARTICLE_COLLISION_GROUP_DEBRIS = 0x5,
            PARTICLE_COLLISION_GROUP_INTERACTIVE = 0x7,
            PARTICLE_COLLISION_GROUP_PLAYER = 0x8,
            PARTICLE_COLLISION_GROUP_VEHICLE = 0xA,
            PARTICLE_COLLISION_GROUP_NPC = 0xC,
            PARTICLE_COLLISION_GROUP_PROPS = 0x18,
        },
        DetailCombo_t = {
            DETAIL_COMBO_OFF = 0x0,
            DETAIL_COMBO_ADD = 0x1,
            DETAIL_COMBO_ADD_SELF_ILLUM = 0x2,
            DETAIL_COMBO_MOD2X = 0x3,
        },
        ScalarExpressionType_t = {
            SCALAR_EXPRESSION_UNINITIALIZED = -1,
            SCALAR_EXPRESSION_ADD = 0x0,
            SCALAR_EXPRESSION_SUBTRACT = 0x1,
            SCALAR_EXPRESSION_MUL = 0x2,
            SCALAR_EXPRESSION_DIVIDE = 0x3,
            SCALAR_EXPRESSION_INPUT_1 = 0x4,
            SCALAR_EXPRESSION_MIN = 0x5,
            SCALAR_EXPRESSION_MAX = 0x6,
            SCALAR_EXPRESSION_MOD = 0x7,
            SCALAR_EXPRESSION_EQUAL = 0x8,
            SCALAR_EXPRESSION_GT = 0x9,
            SCALAR_EXPRESSION_LT = 0xA,
        },
        SpriteCardPerParticleScale_t = {
            SPRITECARD_TEXTURE_PP_SCALE_NONE = 0x0,
            SPRITECARD_TEXTURE_PP_SCALE_PARTICLE_AGE = 0x1,
            SPRITECARD_TEXTURE_PP_SCALE_ANIMATION_FRAME = 0x2,
            SPRITECARD_TEXTURE_PP_SCALE_SHADER_EXTRA_DATA1 = 0x3,
            SPRITECARD_TEXTURE_PP_SCALE_SHADER_EXTRA_DATA2 = 0x4,
            SPRITECARD_TEXTURE_PP_SCALE_PARTICLE_ALPHA = 0x5,
            SPRITECARD_TEXTURE_PP_SCALE_SHADER_RADIUS = 0x6,
            SPRITECARD_TEXTURE_PP_SCALE_ROLL = 0x7,
            SPRITECARD_TEXTURE_PP_SCALE_YAW = 0x8,
            SPRITECARD_TEXTURE_PP_SCALE_PITCH = 0x9,
            SPRITECARD_TEXTURE_PP_SCALE_RANDOM = 0xA,
            SPRITECARD_TEXTURE_PP_SCALE_NEG_RANDOM = 0xB,
            SPRITECARD_TEXTURE_PP_SCALE_RANDOM_TIME = 0xC,
            SPRITECARD_TEXTURE_PP_SCALE_NEG_RANDOM_TIME = 0xD,
        },
        BlurFilterType_t = {
            BLURFILTER_GAUSSIAN = 0x0,
            BLURFILTER_BOX = 0x1,
        },
        StandardLightingAttenuationStyle_t = {
            LIGHT_STYLE_OLD = 0x0,
            LIGHT_STYLE_NEW = 0x1,
        },
        ParticleParentSetMode_t = {
            PARTICLE_SET_PARENT_NO = 0x0,
            PARTICLE_SET_PARENT_IMMEDIATE = 0x1,
            PARTICLE_SET_PARENT_ROOT = 0x2,
        },
        ParticleLightingQuality_t = {
            PARTICLE_LIGHTING_PER_PARTICLE = 0x0,
            PARTICLE_LIGHTING_PER_VERTEX = 0x1,
            PARTICLE_LIGHTING_PER_PIXEL = -1,
            PARTICLE_LIGHTING_OVERRIDE_POSITION = 0x2,
            PARTICLE_LIGHTING_OVERRIDE_COLOR = 0x3,
            PARTICLE_LIGHTING_ADD_EXTRA_LIGHT = 0x4,
        },
        ParticleVolumetricSmokeCreationType_t = {
            PARTICLE_VOLUMETRIC_SMOKE_TYPE_CONTINUOUS = 0x0,
            PARTICLE_VOLUMETRIC_SMOKE_TYPE_IMPULSE = 0x1,
        },
        SetStatisticExpressionType_t = {
            SET_EXPRESSION_UNINITIALIZED = -1,
            SET_EXPRESSION_SUM = 0x0,
            SET_EXPRESSION_MEAN = 0x1,
            SET_EXPRESSION_MEDIAN = 0x2,
            SET_EXPRESSION_MODE = 0x3,
            SET_EXPRESSION_STANDARD_DEVIATION = 0x4,
            SET_EXPRESSION_MIN = 0x5,
            SET_EXPRESSION_MAX = 0x6,
        },
        EventTypeSelection_t = {
            PARTICLE_EVENT_TYPE_MASK_NONE = 0x0,
            PARTICLE_EVENT_TYPE_MASK_SPAWNED = 0x1,
            PARTICLE_EVENT_TYPE_MASK_KILLED = 0x2,
            PARTICLE_EVENT_TYPE_MASK_COLLISION = 0x4,
            PARTICLE_EVENT_TYPE_MASK_FIRST_COLLISION = 0x8,
            PARTICLE_EVENT_TYPE_MASK_COLLISION_STOPPED = 0x10,
            PARTICLE_EVENT_TYPE_MASK_KILLED_ON_COLLISION = 0x20,
            PARTICLE_EVENT_TYPE_MASK_USER_1 = 0x40,
            PARTICLE_EVENT_TYPE_MASK_USER_2 = 0x80,
            PARTICLE_EVENT_TYPE_MASK_USER_3 = 0x100,
            PARTICLE_EVENT_TYPE_MASK_USER_4 = 0x200,
        },
        ParticleMassMode_t = {
            PARTICLE_MASSMODE_RADIUS_CUBED = 0x0,
            PARTICLE_MASSMODE_RADIUS_SQUARED = 0x2,
        },
        ParticleHitboxBiasType_t = {
            PARTICLE_HITBOX_BIAS_ENTITY = 0x0,
            PARTICLE_HITBOX_BIAS_HITBOX = 0x1,
        },
        ParticleControlPointAxis_t = {
            PARTICLE_CP_AXIS_X = 0x0,
            PARTICLE_CP_AXIS_Y = 0x1,
            PARTICLE_CP_AXIS_Z = 0x2,
            PARTICLE_CP_AXIS_NEGATIVE_X = 0x3,
            PARTICLE_CP_AXIS_NEGATIVE_Y = 0x4,
            PARTICLE_CP_AXIS_NEGATIVE_Z = 0x5,
        },
        ParticlePinDistance_t = {
            PARTICLE_PIN_DISTANCE_NONE = -1,
            PARTICLE_PIN_DISTANCE_NEIGHBOR = 0x0,
            PARTICLE_PIN_DISTANCE_FARTHEST = 0x1,
            PARTICLE_PIN_DISTANCE_FIRST = 0x2,
            PARTICLE_PIN_DISTANCE_LAST = 0x3,
            PARTICLE_PIN_DISTANCE_CENTER = 0x5,
            PARTICLE_PIN_DISTANCE_CP = 0x6,
            PARTICLE_PIN_DISTANCE_CP_PAIR_EITHER = 0x7,
            PARTICLE_PIN_DISTANCE_CP_PAIR_BOTH = 0x8,
            PARTICLE_PIN_SPEED = 0x9,
            PARTICLE_PIN_COLLECTION_AGE = 0xA,
            PARTICLE_PIN_FLOAT_VALUE = 0xB,
        },
        VectorFloatExpressionType_t = {
            VECTOR_FLOAT_EXPRESSION_UNINITIALIZED = -1,
            VECTOR_FLOAT_EXPRESSION_DOTPRODUCT = 0x0,
            VECTOR_FLOAT_EXPRESSION_DISTANCE = 0x1,
            VECTOR_FLOAT_EXPRESSION_DISTANCESQR = 0x2,
            VECTOR_FLOAT_EXPRESSION_INPUT1_LENGTH = 0x3,
            VECTOR_FLOAT_EXPRESSION_INPUT1_LENGTHSQR = 0x4,
            VECTOR_FLOAT_EXPRESSION_INPUT1_NOISE = 0x5,
        },
        ParticleFogType_t = {
            PARTICLE_FOG_GAME_DEFAULT = 0x0,
            PARTICLE_FOG_ENABLED = 0x1,
            PARTICLE_FOG_DISABLED = 0x2,
        },
        VectorExpressionType_t = {
            VECTOR_EXPRESSION_UNINITIALIZED = -1,
            VECTOR_EXPRESSION_ADD = 0x0,
            VECTOR_EXPRESSION_SUBTRACT = 0x1,
            VECTOR_EXPRESSION_MUL = 0x2,
            VECTOR_EXPRESSION_DIVIDE = 0x3,
            VECTOR_EXPRESSION_INPUT_1 = 0x4,
            VECTOR_EXPRESSION_MIN = 0x5,
            VECTOR_EXPRESSION_MAX = 0x6,
            VECTOR_EXPRESSION_CROSSPRODUCT = 0x7,
            VECTOR_EXPRESSION_LERP = 0x8,
        },
        ParticleMultiSegmentInputSelection_t = {
            PARTICLE_MULTISEGMENT_SELECTION_FLOAT = 0x0,
            PARTICLE_MULTISEGMENT_SELECTION_STRING = 0x1,
        },
        ParticleRotationLockType_t = {
            PARTICLE_ROTATION_LOCK_NONE = 0x0,
            PARTICLE_ROTATION_LOCK_ROTATIONS = 0x1,
            PARTICLE_ROTATION_LOCK_NORMAL = 0x2,
        },
        HitboxLerpType_t = {
            HITBOX_LERP_LIFETIME = 0x0,
            HITBOX_LERP_CONSTANT = 0x1,
        },
        ParticleAttrBoxFlags_t = {
            PARTICLE_ATTR_BOX_FLAGS_NONE = 0x0,
            PARTICLE_ATTR_BOX_FLAGS_WATER = 0x1,
            PARTICLE_ATTR_BOX_FLAGS_ON_FIRE = 0x2,
            PARTICLE_ATTR_BOX_FLAGS_ELECTRIFIED = 0x4,
            PARTICLE_ATTR_BOX_FLAGS_ASLEEP = 0x8,
            PARTICLE_ATTR_BOX_FLAGS_FROZEN = 0x10,
            PARTICLE_ATTR_BOX_FLAGS_TIMED_DECAY = 0x20,
        },
        ParticleTopology_t = {
            PARTICLE_TOPOLOGY_POINTS = 0x0,
            PARTICLE_TOPOLOGY_LINES = 0x1,
            PARTICLE_TOPOLOGY_TRIS = 0x2,
            PARTICLE_TOPOLOGY_QUADS = 0x3,
            PARTICLE_TOPOLOGY_CUBES = 0x4,
        },
        ParticleLightBehaviorChoiceList_t = {
            PARTICLE_LIGHT_BEHAVIOR_FOLLOW_DIRECTION = 0x0,
            PARTICLE_LIGHT_BEHAVIOR_ROPE = 0x1,
            PARTICLE_LIGHT_BEHAVIOR_TRAILS = 0x2,
        },
        ModelHitboxType_t = {
            MODEL_HITBOX_TYPE_STANDARD = 0x0,
            MODEL_HITBOX_TYPE_RAW_BONES = 0x1,
            MODEL_HITBOX_TYPE_RENDERBOUNDS = 0x2,
            MODEL_HITBOX_TYPE_SNAPSHOT = 0x3,
        },
        ParticleMultiSegmentCountSelection_t = {
            PARTICLE_MULTISEGMENT_SEG_COUNT_7 = 0x7,
            PARTICLE_MULTISEGMENT_SEG_COUNT_14 = 0xE,
            PARTICLE_MULTISEGMENT_SEG_COUNT_16 = 0x10,
        },
        ParticleOrientationType_t = {
            PARTICLE_ORIENTATION_NONE = 0x0,
            PARTICLE_ORIENTATION_VELOCITY = 0x1,
            PARTICLE_ORIENTATION_NORMAL = 0x2,
            PARTICLE_ORIENTATION_ROTATION = 0x4,
        },
        ParticleTraceSet_t = {
            PARTICLE_TRACE_SET_ALL = 0x0,
            PARTICLE_TRACE_SET_STATIC = 0x1,
            PARTICLE_TRACE_SET_STATIC_AND_KEYFRAMED = 0x2,
            PARTICLE_TRACE_SET_DYNAMIC = 0x3,
        },
        ParticleTextureLayerBlendType_t = {
            SPRITECARD_TEXTURE_BLEND_MULTIPLY = 0x0,
            SPRITECARD_TEXTURE_BLEND_MOD2X = 0x1,
            SPRITECARD_TEXTURE_BLEND_REPLACE = 0x2,
            SPRITECARD_TEXTURE_BLEND_ADD = 0x3,
            SPRITECARD_TEXTURE_BLEND_SUBTRACT = 0x4,
            SPRITECARD_TEXTURE_BLEND_AVERAGE = 0x5,
            SPRITECARD_TEXTURE_BLEND_LUMINANCE = 0x6,
        },
        ParticleSelection_t = {
            PARTICLE_SELECTION_FIRST = 0x0,
            PARTICLE_SELECTION_LAST = 0x1,
            PARTICLE_SELECTION_NUMBER = 0x2,
        },
        ParticleToolsState_t = {
            PARTICLE_TOOLS_STATE_ALWAYS_ON = -1,
            PARTICLE_TOOLS_STATE_TOOLS_ONLY = 0x0,
            PARTICLE_TOOLS_STATE_GAME_ONLY = 0x1,
        },
        SnapshotIndexType_t = {
            SNAPSHOT_INDEX_INCREMENT = 0x0,
            SNAPSHOT_INDEX_DIRECT = 0x1,
        },
        ParticleOutputBlendMode_t = {
            PARTICLE_OUTPUT_BLEND_MODE_ALPHA = 0x0,
            PARTICLE_OUTPUT_BLEND_MODE_ADD = 0x1,
            PARTICLE_OUTPUT_BLEND_MODE_BLEND_ADD = 0x2,
            PARTICLE_OUTPUT_BLEND_MODE_HALF_BLEND_ADD = 0x3,
            PARTICLE_OUTPUT_BLEND_MODE_NEG_HALF_BLEND_ADD = 0x4,
            PARTICLE_OUTPUT_BLEND_MODE_MOD2X = 0x5,
            PARTICLE_OUTPUT_BLEND_MODE_LIGHTEN = 0x6,
        },
        ParticleLightnintBranchBehavior_t = {
            PARTICLE_LIGHTNING_BRANCH_CURRENT_DIR = 0x0,
            PARTICLE_LIGHTNING_BRANCH_ENDPOINT_DIR = 0x1,
        },
        MaterialProxyType_t = {
            MATERIAL_PROXY_STATUS_EFFECT = 0x0,
            MATERIAL_PROXY_TINT = 0x1,
        },
        ParticleDepthFeatheringMode_t = {
            PARTICLE_DEPTH_FEATHERING_OFF = 0x0,
            PARTICLE_DEPTH_FEATHERING_ON_OPTIONAL = 0x1,
            PARTICLE_DEPTH_FEATHERING_ON_REQUIRED = 0x2,
        },
        ParticleLightUnitChoiceList_t = {
            PARTICLE_LIGHT_UNIT_CANDELAS = 0x0,
            PARTICLE_LIGHT_UNIT_LUMENS = 0x1,
        },
        ParticleMultiSegmentSpecialCharacter_t = {
            PARTICLE_MULTISEGMENT_SPECIAL_NONE = -1,
            PARTICLE_MULTISEGMENT_SPECIAL_DECIMAL = 0x0,
            PARTICLE_MULTISEGMENT_SPECIAL_COLON = 0x1,
            PARTICLE_MULTISEGMENT_SPECIAL_DEGREES = 0x2,
        },
        ParticleFalloffFunction_t = {
            PARTICLE_FALLOFF_CONSTANT = 0x0,
            PARTICLE_FALLOFF_LINEAR = 0x1,
            PARTICLE_FALLOFF_EXPONENTIAL = 0x2,
        },
        ParticleSequenceCropOverride_t = {
            PARTICLE_SEQUENCE_CROP_OVERRIDE_DEFAULT = -1,
            PARTICLE_SEQUENCE_CROP_OVERRIDE_FORCE_OFF = 0x0,
            PARTICLE_SEQUENCE_CROP_OVERRIDE_FORCE_ON = 0x1,
        },
        ParticleDetailLevel_t = {
            PARTICLEDETAIL_LOW = 0x0,
            PARTICLEDETAIL_MEDIUM = 0x1,
            PARTICLEDETAIL_HIGH = 0x2,
            PARTICLEDETAIL_ULTRA = 0x3,
        },
        BBoxVolumeType_t = {
            BBOX_VOLUME = 0x0,
            BBOX_DIMENSIONS = 0x1,
            BBOX_MINS_MAXS = 0x2,
            BBOX_RADIUS = 0x3,
        },
        SpriteCardTextureType_t = {
            SPRITECARD_TEXTURE_DIFFUSE = 0x0,
            SPRITECARD_TEXTURE_ZOOM = 0x1,
            SPRITECARD_TEXTURE_1D_COLOR_LOOKUP = 0x2,
            SPRITECARD_TEXTURE_UVDISTORTION = 0x3,
            SPRITECARD_TEXTURE_UVDISTORTION_ZOOM = 0x4,
            SPRITECARD_TEXTURE_NORMALMAP = 0x5,
            SPRITECARD_TEXTURE_ANIMMOTIONVEC = 0x6,
            SPRITECARD_TEXTURE_SPHERICAL_HARMONICS_A = 0x7,
            SPRITECARD_TEXTURE_SPHERICAL_HARMONICS_B = 0x8,
            SPRITECARD_TEXTURE_SPHERICAL_HARMONICS_C = 0x9,
            SPRITECARD_TEXTURE_DEPTH = 0xA,
            SPRITECARD_TEXTURE_ILLUMINATION_GRADIENT = 0xB,
        },
        ParticleAlphaReferenceType_t = {
            PARTICLE_ALPHA_REFERENCE_ALPHA_ALPHA = 0x0,
            PARTICLE_ALPHA_REFERENCE_OPAQUE_ALPHA = 0x1,
            PARTICLE_ALPHA_REFERENCE_ALPHA_OPAQUE = 0x2,
            PARTICLE_ALPHA_REFERENCE_OPAQUE_OPAQUE = 0x3,
        },
        SpriteCardTextureChannel_t = {
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGB = 0x0,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGBA = 0x1,
            SPRITECARD_TEXTURE_CHANNEL_MIX_A = 0x2,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGB_A = 0x3,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGB_ALPHAMASK = 0x4,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGB_RGBMASK = 0x5,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGBA_RGBALPHA = 0x6,
            SPRITECARD_TEXTURE_CHANNEL_MIX_A_RGBALPHA = 0x7,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RGB_A_RGBALPHA = 0x8,
            SPRITECARD_TEXTURE_CHANNEL_MIX_R = 0x9,
            SPRITECARD_TEXTURE_CHANNEL_MIX_G = 0xA,
            SPRITECARD_TEXTURE_CHANNEL_MIX_B = 0xB,
            SPRITECARD_TEXTURE_CHANNEL_MIX_RALPHA = 0xC,
            SPRITECARD_TEXTURE_CHANNEL_MIX_GALPHA = 0xD,
            SPRITECARD_TEXTURE_CHANNEL_MIX_BALPHA = 0xE,
        },
        ParticleVolumetricSmokeType_t = {
            PARTICLE_VOLUMETRIC_SMOKE_TYPE_EMISSION = 0x0,
            PARTICLE_VOLUMETRIC_SMOKE_TYPE_SINK = 0x1,
            PARTICLE_VOLUMETRIC_SMOKE_TYPE_REPEL = 0x2,
        },
        RenderModelSubModelFieldType_t = {
            SUBMODEL_AS_BODYGROUP_SUBMODEL = 0x0,
            SUBMODEL_AS_MESHGROUP_INDEX = 0x1,
            SUBMODEL_AS_MESHGROUP_MASK = 0x2,
            SUBMODEL_IGNORED_USE_MODEL_DEFAULT_MESHGROUP_MASK = 0x3,
        },
        ParticleHitboxDataSelection_t = {
            PARTICLE_HITBOX_AVERAGE_SPEED = 0x0,
            PARTICLE_HITBOX_COUNT = 0x1,
        },
        ParticleOrientationChoiceList_t = {
            PARTICLE_ORIENTATION_SCREEN_ALIGNED = 0x0,
            PARTICLE_ORIENTATION_SCREEN_Z_ALIGNED = 0x1,
            PARTICLE_ORIENTATION_WORLD_Z_ALIGNED = 0x2,
            PARTICLE_ORIENTATION_ALIGN_TO_PARTICLE_NORMAL = 0x3,
            PARTICLE_ORIENTATION_SCREENALIGN_TO_PARTICLE_NORMAL = 0x4,
            PARTICLE_ORIENTATION_FULL_3AXIS_ROTATION = 0x5,
        },
        ParticleCollisionMode_t = {
            COLLISION_MODE_PER_PARTICLE_TRACE = 0x3,
            COLLISION_MODE_USE_NEAREST_TRACE = 0x2,
            COLLISION_MODE_PER_FRAME_PLANESET = 0x1,
            COLLISION_MODE_INITIAL_TRACE_DOWN = 0x0,
            COLLISION_MODE_DISABLED = -1,
        },
        ParticleSortingChoiceList_t = {
            PARTICLE_SORTING_NEAREST = 0x0,
            PARTICLE_SORTING_CREATION_TIME = 0x1,
        },
        ParticleEndcapMode_t = {
            PARTICLE_ENDCAP_ALWAYS_ON = -1,
            PARTICLE_ENDCAP_ENDCAP_OFF = 0x0,
            PARTICLE_ENDCAP_ENDCAP_ON = 0x1,
        },
        ClosestPointTestType_t = {
            PARTICLE_CLOSEST_TYPE_BOX = 0x0,
            PARTICLE_CLOSEST_TYPE_CAPSULE = 0x1,
            PARTICLE_CLOSEST_TYPE_HYBRID = 0x2,
        },
        ParticleImpulseType_t = {
            IMPULSE_TYPE_NONE = 0x0,
            IMPULSE_TYPE_GENERIC = 0x1,
            IMPULSE_TYPE_ROPE = 0x2,
            IMPULSE_TYPE_EXPLOSION = 0x4,
            IMPULSE_TYPE_EXPLOSION_UNDERWATER = 0x8,
            IMPULSE_TYPE_PARTICLE_SYSTEM = 0x10,
        },
        ParticleLiquidContents_t = {
            PARTICLE_LIQUID_NONE = 0x0,
            PARTICLE_LIQUID_OIL = 0x1,
            PARTICLE_LIQUID_WATER = 0x2,
        },
        SpriteCardShaderType_t = {
            SPRITECARD_SHADER_BASE = 0x0,
            SPRITECARD_SHADER_CUSTOM = 0x1,
        },
        ParticleOmni2LightTypeChoiceList_t = {
            PARTICLE_OMNI2_LIGHT_TYPE_POINT = 0x0,
            PARTICLE_OMNI2_LIGHT_TYPE_SPHERE = 0x1,
        },
        ParticleLightFogLightingMode_t = {
            PARTICLE_LIGHT_FOG_LIGHTING_MODE_NONE = 0x0,
            PARTICLE_LIGHT_FOG_LIGHTING_MODE_DYNAMIC = 0x2,
            PARTICLE_LIGHT_FOG_LIGHTING_MODE_DYNAMIC_NOSHADOWS = 0x4,
        },
        ParticleLightTypeChoiceList_t = {
            PARTICLE_LIGHT_TYPE_POINT = 0x0,
            PARTICLE_LIGHT_TYPE_SPOT = 0x1,
            PARTICLE_LIGHT_TYPE_FX = 0x2,
            PARTICLE_LIGHT_TYPE_CAPSULE = 0x3,
        },
        ParticleOrientationSetMode_t = {
            PARTICLE_ORIENTATION_SET_NONE = -1,
            PARTICLE_ORIENTATION_SET_FROM_VELOCITY = 0x0,
            PARTICLE_ORIENTATION_SET_FROM_NORMAL = 0x1,
            PARTICLE_ORIENTATION_SET_FROM_ROTATIONS = 0x2,
        },
        ParticleCollisionMask_t = {
            PARTICLE_MASK_ALL = -1,
            PARTICLE_MASK_SOLID = 0xC3001,
            PARTICLE_MASK_WATER = 0x18000,
            PARTICLE_MASK_SOLID_WATER = 0xDB001,
            PARTICLE_MASK_SHOT = 0x1C1003,
            PARTICLE_MASK_SHOT_BRUSHONLY = 0x101001,
            PARTICLE_MASK_SHOT_HULL = 0x1C3001,
            PARTICLE_MASK_OPAQUE = 0x80,
            PARTICLE_MASK_DEFAULTPLAYERSOLID = 0xC3011,
            PARTICLE_MASK_NPCSOLID = 0xC3021,
        },
        TextureRepetitionMode_t = {
            TEXTURE_REPETITION_PARTICLE = 0x0,
            TEXTURE_REPETITION_PATH = 0x1,
        },
        CPulseCell_WaitForCursorsWithTag = {
        },
        CPulseCell_Base = {
             = 0x0, -- 
        },
        CPulse_ResumePoint = {
        },
        CPulseCell_PickBestOutflowSelector = {
        },
        CParticleBindingRealPulse = {
        },
        CPulseCell_WaitForObservable = {
        },
        CPulse_OutflowConnection = {
        },
        CPulseGraphDef = {
             = 0x0, -- 
        },
        CPulseCell_FireCursors = {
        },
        CPulseCell_Timeline__TimelineEvent_t = {
             = 0x0, -- 
        },
        CPulseCell_IntervalTimer__CursorState_t = {
             = 0x0, -- 
        },
        CPulseCell_BaseRequirement = {
        },
        CPulseCell_BaseState = {
        },
        OutflowWithRequirements_t = {
             = 0x0, -- 
        },
        CPulseCell_IsRequirementValid = {
        },
        CPulseCell_Value_Gradient = {
        },
        CPulseCursorFuncs = {
        },
        PulseNodeDynamicOutflows_t__DynamicOutflow_t = {
             = 0x0, -- 
        },
        CBasePulseGraphInstance = {
        },
        CPulseCell_Inflow_GraphHook = {
        },
        SignatureOutflow_Resume = {
        },
        CPulseCell_Inflow_BaseEntrypoint = {
        },
        CPulseCell_WaitForCursorsWithTagBase = {
        },
        CPulse_InvokeBinding = {
             = 0x0, -- 
        },
        CPulseCell_IntervalTimer = {
        },
        CPulseTestScriptLib = {
        },
        CPulseCell_BaseLerp = {
        },
        CPulseCell_Value_Curve = {
        },
        CPulseCell_Inflow_EventHandler = {
        },
        CPulseCell_BaseFlow = {
        },
        CPulseCell_Outflow_CycleShuffled__InstanceState_t = {
             = 0x0, -- 
        },
        CPulseCell_BaseLerp__CursorState_t = {
             = 0x0, -- 
        },
        CPulseCell_WaitForCursorsWithTagBase__CursorState_t = {
        },
        CPulseArraylib = {
        },
        SignatureOutflow_Continue = {
        },
        CPulseCell_Timeline = {
        },
        CPulseCell_Inflow_EntOutputHandler = {
        },
        CPulseCell_Outflow_CycleOrdered__InstanceState_t = {
             = 0x0, -- 
        },
        CParticleCollectionBindingInstance = {
        },
        CPulseCell_LimitCount__InstanceState_t = {
             = 0x0, -- 
        },
        CPulseCell_Step_DebugLog = {
        },
        CPulseCell_BaseYieldingInflow = {
        },
        PulseNodeDynamicOutflows_t = {
             = 0x0, -- 
        },
        CPulseCell_IsRequirementValid__Criteria_t = {
        },
        CPulseCell_Inflow_ObservableVariableListener = {
        },
        CPulseCell_Outflow_CycleOrdered = {
        },
        PulseSelectorOutflowList_t = {
             = 0x0, -- 
        },
        CPulseCell_Inflow_Wait = {
        },
        CPulseCell_Outflow_CycleShuffled = {
        },
        CPulseCell_Inflow_Method = {
        },
        CPulseCell_BaseValue = {
        },
        CPulseCell_BooleanSwitchState = {
        },
        CPulseCell_Inflow_Yield = {
        },
        CPulseMathlib = {
        },
        CPulseCell_Unknown = {
        },
        CPulseCell_Outflow_CycleRandom = {
        },
        CPulseCell_Step_PublicOutput = {
        },
        CPulse_BlackboardReference = {
             = 0x0, -- 
        },
        CPulseCell_Value_RandomInt = {
        },
        CPulse_CallInfo = {
             = 0x0, -- 
        },
        CPulseCell_InlineNodeSkipSelector = {
        },
        CPulseCell_LimitCount = {
        },
        CPulseCell_Step_CallExternalMethod = {
        },
        PulseObservableBoolExpression_t = {
             = 0x0, -- 
        },
        CPulseCell_LimitCount__Criteria_t = {
        },
        CPulseCell_CursorQueue = {
        },
        CPulseCell_Value_RandomFloat = {
        },
        CPulseExecCursor = {
        },
        IParticleCollection = {
        },
        ParticleAttributeIndex_t = {
        },
        C_OP_RemapGravityToVector = {
        },
        C_OP_Decay = {
        },
        C_OP_RenderDeferredLight = {
        },
        C_OP_RemapSpeedtoCP = {
        },
        C_OP_RemapTransformToVelocity = {
        },
        CollisionGroupContext_t = {
             = 0x0, -- 
        },
        CParticleFunctionPreEmission = {
        },
        C_OP_FadeOutSimple = {
        },
        C_OP_SpringToVectorConstraint = {
        },
        C_OP_RenderRopes = {
        },
        C_INIT_StatusEffectCitadel = {
        },
        C_OP_RenderSound = {
        },
        CParticleVisibilityInputs = {
             = 0x0, -- 
        },
        C_OP_SetControlPointsToParticle = {
        },
        C_OP_RemapCPVelocityToVector = {
        },
        C_OP_PointVectorAtNextParticle = {
        },
        ParticlePreviewBodyGroup_t = {
             = 0x0, -- 
        },
        C_OP_OscillateScalarSimple = {
        },
        C_INIT_StatusEffect = {
        },
        C_INIT_RtEnvCull = {
        },
        C_OP_ConstrainDistance = {
        },
        C_INIT_RandomVector = {
        },
        C_INIT_InitialVelocityNoise = {
        },
        ParticleChildrenInfo_t = {
        },
        C_OP_RemapScalarOnceTimed = {
        },
        C_INIT_RandomNamedModelSequence = {
        },
        C_OP_PlaneCull = {
        },
        C_INIT_VelocityRandom = {
        },
        C_OP_ModelDampenMovement = {
        },
        C_OP_TwistAroundAxis = {
        },
        C_OP_TeleportBeam = {
        },
        C_OP_RemapExternalWindToCP = {
        },
        CBaseRendererSource2 = {
        },
        CSpinUpdateBase = {
        },
        C_OP_OrientTo2dDirection = {
        },
        C_OP_RemapDotProductToCP = {
        },
        C_INIT_RemapParticleCountToNamedModelElementScalar = {
        },
        C_OP_RenderTrails = {
        },
        C_OP_SetControlPointPositionToTimeOfDayValue = {
        },
        C_OP_DecayMaintainCount = {
        },
        C_INIT_RandomModelSequence = {
        },
        C_OP_ExternalGameImpulseForce = {
        },
        C_OP_RemapAverageHitboxSpeedtoCP = {
        },
        C_INIT_RandomAlpha = {
        },
        C_OP_NormalizeVector = {
        },
        C_OP_FadeInSimple = {
        },
        C_OP_RepeatedTriggerChildGroup = {
        },
        C_OP_RemapVelocityToVector = {
        },
        C_INIT_SetHitboxToClosest = {
        },
        C_INIT_RingWave = {
        },
        C_INIT_RandomTrailLength = {
        },
        C_OP_RemapScalar = {
        },
        C_OP_DistanceBetweenTransforms = {
        },
        C_OP_DecayOffscreen = {
        },
        C_INIT_CreateSequentialPath = {
        },
        C_OP_EndCapTimedDecay = {
        },
        C_OP_RemapDistanceToLineSegmentBase = {
        },
        C_OP_ContinuousEmitter = {
        },
        C_OP_OscillateVectorSimple = {
        },
        C_INIT_SequenceLifeTime = {
        },
        C_INIT_MoveBetweenPoints = {
        },
        C_OP_SetUserEvent = {
        },
        C_OP_QuantizeFloat = {
        },
        C_OP_BasicMovement = {
        },
        C_INIT_RandomNamedModelElement = {
        },
        C_INIT_InitFromParentKilled = {
        },
        C_OP_Callback = {
        },
        CParticleFunction = {
        },
        C_OP_GlobalLight = {
        },
        C_INIT_OffsetVectorToVector = {
        },
        C_OP_SetPerChildControlPointFromAttribute = {
        },
        C_OP_SetParentControlPointsToChildCP = {
        },
        C_OP_BoxConstraint = {
        },
        C_INIT_CreatePhyllotaxis = {
        },
        C_OP_AttractToControlPoint = {
        },
        C_INIT_RandomLifeTime = {
        },
        C_INIT_RemapParticleCountToNamedModelSequenceScalar = {
        },
        C_INIT_VelocityRadialRandom = {
        },
        C_INIT_RandomRadius = {
        },
        C_OP_Orient2DRelToCP = {
        },
        TextureControls_t = {
             = 0x0, -- 
        },
        ControlPointReference_t = {
             = 0x0, -- 
        },
        C_OP_SetControlPointToVectorExpression = {
        },
        C_OP_LightningSnapshotGenerator = {
        },
        C_OP_RemapNamedModelMeshGroupOnceTimed = {
        },
        C_INIT_RemapQAnglesToRotation = {
        },
        C_INIT_PositionWarp = {
        },
        C_OP_SetControlPointFieldToScalarExpression = {
        },
        C_OP_CreateParticleSystemRenderer = {
        },
        CParticleFunctionForce = {
        },
        C_INIT_RandomVectorComponent = {
        },
        C_OP_InheritFromParentParticles = {
        },
        C_INIT_SetVectorAttributeToVectorExpression = {
        },
        C_OP_RemapTransformVisibilityToVector = {
        },
        C_OP_DirectionBetweenVecsToVec = {
        },
        C_OP_MovementLoopInsideSphere = {
        },
        C_OP_RenderSimpleModelCollection = {
        },
        C_OP_QuantizeCPComponent = {
        },
        C_OP_PlayEndCapWhenFinished = {
        },
        C_INIT_InitFloatCollection = {
        },
        CPathParameters = {
        },
        C_OP_RemapScalarEndCap = {
        },
        C_INIT_CreateFromPlaneCache = {
        },
        C_OP_LazyCullCompareFloat = {
        },
        C_OP_ControlPointToRadialScreenSpace = {
        },
        C_OP_SpinUpdate = {
        },
        C_INIT_NormalOffset = {
        },
        C_OP_RemapDistanceToLineSegmentToVector = {
        },
        C_OP_RenderAsModels = {
        },
        C_INIT_CreationNoise = {
        },
        C_OP_Spin = {
        },
        C_OP_GameLiquidSpill = {
        },
        C_OP_InstantaneousEmitter = {
        },
        C_OP_ConstrainLineLength = {
        },
        C_INIT_LifespanFromVelocity = {
        },
        CBaseTrailRenderer = {
        },
        C_INIT_VelocityFromCP = {
        },
        C_OP_SetControlPointOrientation = {
        },
        C_OP_MovementSkinnedPositionFromCPSnapshot = {
        },
        C_OP_MultiSegmentDisplaySnapshotGenerator = {
        },
        C_OP_OscillateVector = {
        },
        C_OP_PositionLock = {
        },
        C_OP_RenderVRHapticEvent = {
        },
        C_OP_SetControlPointToImpactPoint = {
        },
        C_OP_InterpolateRadius = {
        },
        C_OP_ReinitializeScalarEndCap = {
        },
        C_OP_TurbulenceForce = {
        },
        C_OP_RemapNamedModelElementOnceTimed = {
        },
        C_OP_SetControlPointToPlayer = {
        },
        C_OP_EndCapTimedFreeze = {
        },
        C_OP_RenderGpuImplicit = {
        },
        C_OP_SetRandomControlPointPosition = {
        },
        C_OP_RenderVolumetricEmitter = {
        },
        C_OP_RemapTransformVisibilityToScalar = {
        },
        C_OP_RemapControlPointDirectionToVector = {
        },
        C_OP_ScreenSpacePositionOfTarget = {
        },
        CParticleFunctionOperator = {
        },
        C_OP_DragRelativeToPlane = {
        },
        C_OP_SetCPtoVector = {
        },
        C_INIT_RandomYaw = {
        },
        C_OP_SnapshotRigidSkinToBones = {
        },
        C_OP_SetSingleControlPointPosition = {
        },
        C_INIT_DistanceToNeighborCull = {
        },
        C_OP_RemapCPtoScalar = {
        },
        CParticleFunctionRenderer = {
        },
        CParticleSystemDefinition = {
        },
        C_OP_RemapNamedModelMeshGroupEndCap = {
        },
        C_OP_PercentageBetweenTransformsVector = {
        },
        C_OP_RenderScreenVelocityRotate = {
        },
        C_OP_UpdateLightSource = {
        },
        C_INIT_CreateWithinBox = {
        },
        C_OP_ChooseRandomChildrenInGroup = {
        },
        C_OP_ControlpointLight = {
        },
        C_OP_VectorFieldSnapshot = {
        },
        C_OP_CylindricalDistanceToTransform = {
        },
        C_INIT_PositionPlaceOnGround = {
        },
        C_INIT_RandomScalar = {
        },
        C_OP_RenderPostProcessing = {
        },
        C_OP_WorldTraceConstraint = {
        },
        C_OP_RenderBlobs = {
        },
        C_OP_OscillateScalar = {
        },
        C_OP_FadeOut = {
        },
        C_OP_WaterImpulseRenderer = {
        },
        C_INIT_RandomSequence = {
        },
        C_OP_RampScalarSplineSimple = {
        },
        C_INIT_DistanceCull = {
        },
        C_OP_CollideWithParentParticles = {
        },
        C_INIT_InitFromVectorFieldSnapshot = {
        },
        C_OP_SetVectorAttributeToVectorExpression = {
        },
        C_INIT_AddVectorToVector = {
        },
        C_INIT_RemapInitialVisibilityScalar = {
        },
        C_OP_RemapTransformOrientationToYaw = {
        },
        C_OP_RenderStatusEffect = {
        },
        C_OP_RandomForce = {
        },
        C_OP_RemapParticleCountOnScalarEndCap = {
        },
        ParticlePreviewState_t = {
             = 0x0, -- 
        },
        C_OP_LocalAccelerationForce = {
        },
        C_OP_ModelCull = {
        },
        C_OP_SetFloat = {
        },
        C_INIT_RemapTransformToVector = {
        },
        C_OP_ScreenSpaceDistanceToEdge = {
        },
        C_OP_RemapDistanceToLineSegmentToScalar = {
        },
        C_OP_RemapVectortoCP = {
        },
        C_OP_SetFromCPSnapshot = {
        },
        C_OP_DistanceBetweenCPsToCP = {
        },
        C_OP_SetControlPointToHand = {
        },
        C_OP_ConstrainDistanceToPath = {
        },
        C_OP_DistanceCull = {
        },
        C_INIT_CreateAlongPath = {
        },
        C_OP_GameDecalRenderer = {
        },
        C_OP_SetControlPointsToModelParticles = {
        },
        C_OP_ColorInterpolateRandom = {
        },
        C_INIT_RemapNamedModelSequenceToScalar = {
        },
        C_OP_RenderLights = {
        },
        C_OP_DecayClampCount = {
        },
        CRandomNumberGeneratorParameters = {
             = 0x0, -- 
        },
        C_INIT_ColorLitPerParticle = {
        },
        C_OP_RenderPoints = {
        },
        C_INIT_SetAttributeToScalarExpression = {
        },
        C_INIT_CreateOnGrid = {
        },
        C_OP_RampCPLinearRandom = {
        },
        C_OP_VelocityMatchingForce = {
        },
        C_INIT_RandomAlphaWindowThreshold = {
        },
        C_INIT_CreateOnModelAtHeight = {
        },
        C_OP_ModelSurfaceSnapshotGenerator = {
        },
        C_OP_RestartAfterDuration = {
        },
        C_OP_RenderClothForce = {
        },
        C_OP_RemapVisibilityScalar = {
        },
        C_INIT_CreateSequentialPathV2 = {
        },
        VecInputMaterialVariable_t = {
             = 0x0, -- 
        },
        C_INIT_RemapInitialDirectionToTransformToVector = {
        },
        C_OP_LockToSavedSequentialPathV2 = {
        },
        C_OP_NormalLock = {
        },
        C_INIT_RemapTransformOrientationToRotations = {
        },
        C_OP_Cull = {
        },
        C_INIT_RandomYawFlip = {
        },
        SequenceWeightedList_t = {
             = 0x0, -- 
        },
        C_OP_ReadFromNeighboringParticle = {
        },
        C_OP_RenderText = {
        },
        C_OP_LerpToInitialPosition = {
        },
        C_INIT_RandomRotation = {
        },
        C_OP_LerpEndCapVector = {
        },
        C_OP_VelocityDecay = {
        },
        C_OP_SetCPOrientationToPointAtCP = {
        },
        C_OP_LockToPointList = {
        },
        C_OP_MovementPlaceOnGround = {
        },
        C_OP_SetCPOrientationToDirection = {
        },
        C_OP_RemapCrossProductOfTwoVectorsToVector = {
        },
        C_OP_RemapTransformOrientationToRotations = {
        },
        C_INIT_RandomRotationSpeed = {
        },
        C_OP_InheritFromParentParticlesV2 = {
        },
        C_INIT_RandomSecondSequence = {
        },
        C_OP_SetFloatCollection = {
        },
        PointDefinition_t = {
             = 0x0, -- 
        },
        C_OP_SetControlPointPositionToRandomActiveCP = {
        },
        C_OP_Diffusion = {
        },
        C_INIT_AgeNoise = {
        },
        C_OP_RemapVectorComponentToScalar = {
        },
        CGeneralRandomRotation = {
        },
        C_OP_DistanceBetweenVecs = {
        },
        C_OP_DampenToCP = {
        },
        C_OP_CalculateVectorAttribute = {
        },
        C_OP_LockToBone = {
        },
        C_OP_RemapNamedModelBodyPartOnceTimed = {
        },
        C_OP_ScreenSpaceRotateTowardTarget = {
        },
        C_OP_MovementMaintainOffset = {
        },
        C_INIT_CreateWithinCapsuleTransform = {
        },
        C_OP_SetVec = {
        },
        C_INIT_CreateFromParentParticles = {
        },
        C_INIT_CheckParticleForWater = {
        },
        C_INIT_RandomNamedModelBodyPart = {
        },
        C_OP_RenderOmni2Light = {
        },
        C_OP_ConnectParentParticleToNearest = {
        },
        CPAssignment_t = {
             = 0x0, -- 
        },
        C_INIT_RemapParticleCountToNamedModelBodyPartScalar = {
        },
        C_INIT_InitSkinnedPositionFromCPSnapshot = {
        },
        C_OP_LagCompensation = {
        },
        C_OP_CollideWithSelf = {
        },
        C_OP_Noise = {
        },
        C_OP_FadeAndKillForTracers = {
        },
        C_OP_ColorAdjustHSL = {
        },
        CParticleMassCalculationParameters = {
             = 0x0, -- 
        },
        C_OP_SequenceFromModel = {
        },
        C_OP_AlphaDecay = {
        },
        C_OP_RemapDensityGradientToVectorAttribute = {
        },
        C_INIT_InitVec = {
        },
        C_INIT_SetHitboxToModel = {
        },
        C_OP_MovementMoveAlongSkinnedCPSnapshot = {
        },
        C_OP_LerpScalar = {
        },
        C_INIT_InitialRepulsionVelocity = {
        },
        C_OP_ClampScalar = {
        },
        C_OP_SetControlPointToHMD = {
        },
        C_OP_DifferencePreviousParticle = {
        },
        C_OP_SetControlPointFieldFromVectorExpression = {
        },
        C_OP_PercentageBetweenTransforms = {
        },
        C_INIT_PlaneCull = {
        },
        C_OP_RemapNamedModelSequenceEndCap = {
        },
        C_INIT_InitFromCPSnapshot = {
        },
        C_OP_RenderCables = {
        },
        C_INIT_InheritVelocity = {
        },
        C_OP_SetControlPointToWaterSurface = {
        },
        C_INIT_PositionOffset = {
        },
        C_INIT_NormalAlignToCP = {
        },
        C_OP_ShapeMatchingConstraint = {
        },
        C_OP_SetChildControlPoints = {
        },
        C_OP_ChladniWave = {
        },
        C_OP_RemapDirectionToCPToVector = {
        },
        C_OP_DriveCPFromGlobalSoundFloat = {
        },
        C_INIT_ScreenSpacePositionOfTarget = {
        },
        C_OP_RtEnvCull = {
        },
        C_OP_PinParticleToCP = {
        },
        C_OP_RemapCPtoVector = {
        },
        C_INIT_CreateParticleImpulse = {
        },
        C_OP_DensityForce = {
        },
        C_INIT_CreateInEpitrochoid = {
        },
        C_OP_ConstrainDistanceToUserSpecifiedPath = {
        },
        C_OP_SetControlPointPositions = {
        },
        C_OP_SetFloatAttributeToVectorExpression = {
        },
        C_OP_MovementRotateParticleAroundAxis = {
        },
        C_OP_IntraParticleForce = {
        },
        C_INIT_InitFloat = {
        },
        C_INIT_CreateOnModel = {
        },
        C_OP_InheritFromPeerSystem = {
        },
        C_OP_PerParticleForce = {
        },
        C_INIT_RandomNamedModelMeshGroup = {
        },
        C_OP_RenderProjected = {
        },
        C_OP_MaxVelocity = {
        },
        C_INIT_VelocityFromNormal = {
        },
        C_OP_MaintainEmitter = {
        },
        C_INIT_PositionOffsetToCP = {
        },
        C_INIT_RemapInitialTransformDirectionToRotation = {
        },
        C_OP_FadeAndKill = {
        },
        C_OP_ColorInterpolate = {
        },
        C_OP_RampScalarSpline = {
        },
        C_OP_RemapNamedModelSequenceOnceTimed = {
        },
        C_OP_SetControlPointFromObjectScale = {
        },
        C_OP_MaintainSequentialPath = {
        },
        C_OP_RemapNamedModelBodyPartEndCap = {
        },
        C_OP_StopAfterCPDuration = {
        },
        CGeneralSpin = {
        },
        C_OP_LockToSavedSequentialPath = {
        },
        C_INIT_RemapNamedModelElementToScalar = {
        },
        C_OP_ClampVector = {
        },
        C_OP_RenderStatusEffectCitadel = {
        },
        IParticleSystemDefinition = {
        },
        C_OP_WindForce = {
        },
        C_OP_SetVariable = {
        },
        C_OP_RenderStandardLight = {
        },
        C_OP_DistanceToTransform = {
        },
        C_OP_RemapControlPointOrientationToRotation = {
        },
        C_OP_SetControlPointToCenter = {
        },
        C_OP_RemapAverageScalarValuetoCP = {
        },
        C_OP_RemapDotProductToScalar = {
        },
        C_OP_RemapCPtoCP = {
        },
        C_OP_SetControlPointRotation = {
        },
        C_OP_CurlNoiseForce = {
        },
        C_INIT_Orient2DRelToCP = {
        },
        C_OP_SetSimulationRate = {
        },
        C_OP_FadeIn = {
        },
        C_OP_RenderScreenShake = {
        },
        C_OP_RemapBoundingVolumetoCP = {
        },
        C_OP_HSVShiftToCP = {
        },
        C_OP_RemapVectorToRotations = {
        },
        C_INIT_GlobalScale = {
        },
        C_INIT_RadiusFromCPObject = {
        },
        C_INIT_InitialVelocityFromHitbox = {
        },
        C_OP_LerpVector = {
        },
        C_OP_SetControlPointFieldToWater = {
        },
        TextureGroup_t = {
             = 0x0, -- 
        },
        C_OP_TimeVaryingForce = {
        },
        C_OP_SetCPOrientationToGroundNormal = {
        },
        C_OP_SnapshotSkinToBones = {
        },
        C_INIT_CreateWithinSphereTransform = {
        },
        C_OP_RadiusDecay = {
        },
        C_INIT_RemapNamedModelBodyPartToScalar = {
        },
        C_INIT_RemapScalarToVector = {
        },
        C_INIT_InitialSequenceFromModel = {
        },
        C_OP_NoiseEmitter = {
        },
        CParticleFunctionInitializer = {
        },
        C_OP_SelectivelyEnableChildren = {
        },
        ModelReference_t = {
             = 0x0, -- 
        },
        C_OP_PlanarConstraint = {
        },
        C_INIT_CreateFromCPs = {
        },
        C_OP_LockPoints = {
        },
        C_INIT_CreateSpiralSphere = {
        },
        C_OP_CPVelocityForce = {
        },
        C_OP_RemapNamedModelElementEndCap = {
        },
        C_INIT_ScaleVelocity = {
        },
        C_OP_MoveToHitbox = {
        },
        C_OP_PinRopeSegmentParticleToParent = {
        },
        C_INIT_PointList = {
        },
        C_OP_LerpToOtherAttribute = {
        },
        C_INIT_RandomColor = {
        },
        C_OP_SetGravityToCP = {
        },
        C_INIT_RemapParticleCountToScalar = {
        },
        C_INIT_InheritFromParentParticles = {
        },
        C_OP_RampScalarLinearSimple = {
        },
        C_INIT_ChaoticAttractor = {
        },
        C_OP_MovementRigidAttachToCP = {
        },
        C_OP_RenderFlattenGrass = {
        },
        C_OP_RenderLightBeam = {
        },
        C_OP_EnableChildrenFromParentParticleCount = {
        },
        C_INIT_DistanceToCPInit = {
        },
        CReplicationParameters = {
             = 0x0, -- 
        },
        C_OP_EndCapDecay = {
        },
        C_OP_ForceBasedOnDistanceToPlane = {
        },
        C_OP_RemapDensityToVector = {
        },
        ParticleControlPointConfiguration_t = {
             = 0x0, -- 
        },
        C_INIT_SetRigidAttachment = {
        },
        MaterialVariable_t = {
             = 0x0, -- 
        },
        CParticleFunctionConstraint = {
        },
        C_OP_RemapSpeed = {
        },
        C_OP_RenderModels = {
        },
        C_OP_RenderClientPhysicsImpulse = {
        },
        CParticleFunctionEmitter = {
        },
        C_INIT_RemapNamedModelMeshGroupToScalar = {
        },
        C_OP_SetControlPointOrientationToCPVelocity = {
        },
        C_OP_RopeSpringConstraint = {
        },
        C_INIT_PositionWarpScalar = {
        },
        C_OP_ForceControlPointStub = {
        },
        C_OP_VectorNoise = {
        },
        C_OP_RemapParticleCountToScalar = {
        },
        C_INIT_QuantizeFloat = {
        },
        C_OP_RemapModelVolumetoCP = {
        },
        C_OP_SetToCP = {
        },
        ParticleControlPointDriver_t = {
             = 0x0, -- 
        },
        C_OP_ParentVortices = {
        },
        C_OP_SetControlPointToCPVelocity = {
        },
        C_OP_ClientPhysics = {
        },
        C_OP_SpinYaw = {
        },
        PointDefinitionWithTimeValues_t = {
        },
        RenderProjectedMaterial_t = {
             = 0x0, -- 
        },
        C_INIT_SetFloatAttributeToVectorExpression = {
        },
        C_OP_ExternalWindForce = {
        },
        C_INIT_ModelCull = {
        },
        C_OP_RenderSprites = {
        },
        C_OP_PercentageBetweenTransformLerpCPs = {
        },
        C_OP_SetPerChildControlPoint = {
        },
        C_OP_RenderTreeShake = {
        },
        C_OP_WorldCollideConstraint = {
        },
        C_OP_SetAttributeToScalarExpression = {
        },
        C_OP_CycleScalar = {
        },
        C_OP_RenderMaterialProxy = {
        },
        FloatInputMaterialVariable_t = {
             = 0x0, -- 
        },
        C_OP_RampScalarLinear = {
        },
        C_OP_RotateVector = {
        },
        C_INIT_InitVecCollection = {
        },
        C_INIT_RemapParticleCountToNamedModelMeshGroupScalar = {
        },
        C_INIT_SequenceFromCP = {
        },
        C_OP_CPOffsetToPercentageBetweenCPs = {
        },
        C_OP_LerpEndCapScalar = {
        },
    },
}
