#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-04-21T01:07:42.863545+00:00
# Build No: 14151
# Classes: 3222 | Enums: 480 | Offsets: 32 | Modules: 18
#

# Module: resourcesystem.dll
class ResourcesystemDll: {
    class FuseVariableType_t: {
        INVALID = 0x0
        BOOL = 0x1
        INT8 = 0x2
        INT16 = 0x3
        INT32 = 0x4
        UINT8 = 0x5
        UINT16 = 0x6
        UINT32 = 0x7
        FLOAT32 = 0x8
    }
    class FuseVariableAccess_t: {
        WRITABLE = 0x0
        READ_ONLY = 0x1
    }
    class InfoForResourceTypeCResponseRulesList: {
        pass
    }
    class InfoForResourceTypeCDotaItemDefinitionResource: {
        pass
    }
    class InfoForResourceTypeCMorphSetData: {
        pass
    }
    class InfoForResourceTypeCVSoundStackScriptList: {
        pass
    }
    class PackedAABB_t: {
        m_nPackedMin = 0x0 # uint32
        m_nPackedMax = 0x4 # uint32
    }
    class InfoForResourceTypeCVPhysXSurfacePropertiesList: {
        pass
    }
    class InfoForResourceTypeManifestTestResource_t: {
        pass
    }
    class ConstantInfo_t: {
        m_name = 0x0 # CUtlString
        m_nameToken = 0x8 # CUtlStringToken
        m_flValue = 0xC # float32
    }
    class FuseFunctionIndex_t: {
        m_Value = 0x0 # uint16
    }
    class InfoForResourceTypeCGcExportableExternalData: {
        pass
    }
    class InfoForResourceTypeIAnimGraphModelBinding: {
        pass
    }
    class InfoForResourceTypeCJavaScriptResource: {
        pass
    }
    class CFuseSymbolTable: {
        m_constants = 0x0 # CUtlVector<ConstantInfo_t>
        m_variables = 0x18 # CUtlVector<VariableInfo_t>
        m_functions = 0x30 # CUtlVector<FunctionInfo_t>
        m_constantMap = 0x48 # CUtlHashtable<CUtlStringToken,int32>
        m_variableMap = 0x68 # CUtlHashtable<CUtlStringToken,int32>
        m_functionMap = 0x88 # CUtlHashtable<CUtlStringToken,int32>
    }
    class InfoForResourceTypeCRenderMesh: {
        pass
    }
    class InfoForResourceTypeCVoxelVisibility: {
        pass
    }
    class InfoForResourceTypeCPhysAggregateData: {
        pass
    }
    class InfoForResourceTypeCNmClip: {
        pass
    }
    class InfoForResourceTypeWorld_t: {
        pass
    }
    class InfoForResourceTypeProceduralTestResource_t: {
        pass
    }
    class AABB_t: {
        m_vMinBounds = 0x0 # Vector
        m_vMaxBounds = 0xC # Vector
    }
    class InfoForResourceTypeCPostProcessingResource: {
        pass
    }
    class VariableInfo_t: {
        m_name = 0x0 # CUtlString
        m_nameToken = 0x8 # CUtlStringToken
        m_nIndex = 0xC # FuseVariableIndex_t
        m_nNumComponents = 0xE # uint8
        m_eVarType = 0xF # FuseVariableType_t
        m_eAccess = 0x10 # FuseVariableAccess_t
    }
    class InfoForResourceTypeIParticleSnapshot: {
        pass
    }
    class FourQuaternions: {
        x = 0x0 # fltx4
        y = 0x10 # fltx4
        z = 0x20 # fltx4
        w = 0x30 # fltx4
    }
    class InfoForResourceTypeCPanoramaLayout: {
        pass
    }
    class InfoForResourceTypeCTypeScriptResource: {
        pass
    }
    class InfoForResourceTypeCChoreoSceneResource: {
        pass
    }
    class InfoForResourceTypeCNmSkeleton: {
        pass
    }
    class InfoForResourceTypeCTestResourceData: {
        pass
    }
    class InfoForResourceTypeCAnimationGroup: {
        pass
    }
    class InfoForResourceTypeCVSoundEventScriptList: {
        pass
    }
    class InfoForResourceTypeCVoiceContainerBase: {
        pass
    }
    class InfoForResourceTypeCPanoramaStyle: {
        pass
    }
    class InfoForResourceTypeCWorldNode: {
        pass
    }
    class InfoForResourceTypeCSurfaceGraph: {
        pass
    }
    class InfoForResourceTypeCCSGOEconItem: {
        pass
    }
    class InfoForResourceTypeCNmGraphDefinition: {
        pass
    }
    class InfoForResourceTypeCSmartProp: {
        pass
    }
    class CFuseProgram: {
        m_programBuffer = 0x0 # CUtlVector<uint8>
        m_variablesRead = 0x18 # CUtlVector<FuseVariableIndex_t>
        m_variablesWritten = 0x30 # CUtlVector<FuseVariableIndex_t>
        m_nMaxTempVarsUsed = 0x48 # int32
    }
    class InfoForResourceTypeCCompositeMaterialKit: {
        pass
    }
    class InfoForResourceTypeCVMixListResource: {
        pass
    }
    class InfoForResourceTypeCAnimData: {
        pass
    }
    class InfoForResourceTypeIMaterial2: {
        pass
    }
    class InfoForResourceTypeIVectorGraphic: {
        pass
    }
    class InfoForResourceTypeCPanoramaDynamicImages: {
        pass
    }
    class InfoForResourceTypeIPulseGraphDef: {
        pass
    }
    class InfoForResourceTypeCVDataItemDefs: {
        pass
    }
    class FunctionInfo_t: {
        m_name = 0x8 # CUtlString
        m_nameToken = 0x10 # CUtlStringToken
        m_nParamCount = 0x14 # int32
        m_nIndex = 0x18 # FuseFunctionIndex_t
        m_bIsPure = 0x1A # bool
    }
    class InfoForResourceTypeCVDataResource: {
        pass
    }
    class InfoForResourceTypeCModel: {
        pass
    }
    class InfoForResourceTypeCDOTANovelsList: {
        pass
    }
    class InfoForResourceTypeCTextureBase: {
        pass
    }
    class FuseVariableIndex_t: {
        m_Value = 0x0 # uint16
    }
    class InfoForResourceTypeIParticleSystemDefinition: {
        pass
    }
    class InfoForResourceTypeCSequenceGroupData: {
        pass
    }
    class ManifestTestResource_t: {
        m_name = 0x0 # CUtlString
        m_child = 0x8 # CStrongHandle<InfoForResourceTypeManifestTestResource_t>
    }
    class InfoForResourceTypeCEntityLump: {
        pass
    }
    class InfoForResourceTypeCDOTAPatchNotesList: {
        pass
    }
}
