//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-04-21T00:48:31.099236600+00:00
// Build No: 14151
// Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
//

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, unused)]

pub mod exitscam {
    pub mod schemas {
        // Module: resourcesystem.dll
        // Class count: 58
        // Enum count: 2
        pub mod resourcesystem_dll {
            // Alignment: 1
            // Member count: 9
            #[repr(u8)]
            pub enum FuseVariableType_t {
                INVALID = 0x0,
                BOOL = 0x1,
                INT8 = 0x2,
                INT16 = 0x3,
                INT32 = 0x4,
                UINT8 = 0x5,
                UINT16 = 0x6,
                UINT32 = 0x7,
                FLOAT32 = 0x8
            }
            // Alignment: 1
            // Member count: 2
            #[repr(u8)]
            pub enum FuseVariableAccess_t {
                WRITABLE = 0x0,
                READ_ONLY = 0x1
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCResponseRulesList {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCDotaItemDefinitionResource {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCMorphSetData {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVSoundStackScriptList {
            }
            // Parent: None
            // Field count: 0
            pub mod PackedAABB_t {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVPhysXSurfacePropertiesList {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeManifestTestResource_t {
            }
            // Parent: None
            // Field count: 1
            pub mod ConstantInfo_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 0
            pub mod FuseFunctionIndex_t {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCGcExportableExternalData {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeIAnimGraphModelBinding {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCJavaScriptResource {
            }
            // Parent: None
            // Field count: 1
            pub mod CFuseSymbolTable {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCRenderMesh {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVoxelVisibility {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCPhysAggregateData {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCNmClip {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeWorld_t {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeProceduralTestResource_t {
            }
            // Parent: None
            // Field count: 0
            pub mod AABB_t {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCPostProcessingResource {
            }
            // Parent: None
            // Field count: 1
            pub mod VariableInfo_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeIParticleSnapshot {
            }
            // Parent: None
            // Field count: 0
            pub mod FourQuaternions {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCPanoramaLayout {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCTypeScriptResource {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCChoreoSceneResource {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCNmSkeleton {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCTestResourceData {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCAnimationGroup {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVSoundEventScriptList {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVoiceContainerBase {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCPanoramaStyle {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCWorldNode {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCSurfaceGraph {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCCSGOEconItem {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCNmGraphDefinition {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCSmartProp {
            }
            // Parent: None
            // Field count: 1
            pub mod CFuseProgram {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCCompositeMaterialKit {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVMixListResource {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCAnimData {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeIMaterial2 {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeIVectorGraphic {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCPanoramaDynamicImages {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeIPulseGraphDef {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVDataItemDefs {
            }
            // Parent: None
            // Field count: 1
            pub mod FunctionInfo_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCVDataResource {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCModel {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCDOTANovelsList {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCTextureBase {
            }
            // Parent: None
            // Field count: 0
            pub mod FuseVariableIndex_t {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeIParticleSystemDefinition {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCSequenceGroupData {
            }
            // Parent: None
            // Field count: 1
            pub mod ManifestTestResource_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCEntityLump {
            }
            // Parent: None
            // Field count: 0
            pub mod InfoForResourceTypeCDOTAPatchNotesList {
            }
        }
    }
}
