#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-04-21T00:48:31.099236600+00:00
# Build No: 14151
# Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
#

# Module: soundsystem.dll
class SoundsystemDll: {
    class SndSeqInstrumentType_t: {
        eSndSeqInstNull = 0x0
        eSndSeqInstSndEvt = 0x1
        eSndSeqInstMidiSampler = 0x2
    }
    class EMode_t: {
        Peak = 0x0
        RMS = 0x1
    }
    class VMixGraphCommandID_t: {
        CMD_INVALID = -1
        CMD_CONTROL_INPUT_STORE = 0x1
        CMD_CONTROL_INPUT_STORE_DB = 0x2
        CMD_CONTROL_TRANSIENT_INPUT_STORE = 0x3
        CMD_CONTROL_TRANSIENT_INPUT_RESET = 0x4
        CMD_CONTROL_OUTPUT_STORE = 0x5
        CMD_CONTROL_EVALUATE_CURVE = 0x6
        CMD_CONTROL_COPY = 0x7
        CMD_CONTROL_COND_COPY_IF_NEGATIVE = 0x8
        CMD_CONTROL_REMAP_LINEAR = 0x9
        CMD_CONTROL_REMAP_SINE = 0xA
        CMD_CONTROL_REMAP_LOGLINEAR = 0xB
        CMD_CONTROL_MAX = 0xC
        CMD_CONTROL_RESET_TIMER = 0xD
        CMD_CONTROL_INCREMENT_TIMER = 0xE
        CMD_CONTROL_EVAL_ENVELOPE = 0xF
        CMD_CONTROL_SINE_BLEND = 0x10
        CMD_PROCESSOR_SET_CONTROL_VALUE = 0x11
        CMD_PROCESSOR_SET_NAME_INPUT = 0x12
        CMD_PROCESSOR_SET_CONTROL_ARRAYVALUE = 0x13
        CMD_PROCESSOR_STORE_CONTROL_VALUE = 0x14
        CMD_PROCESSOR_SET_VSND_VALUE = 0x15
        CMD_SUBMIX_PROCESS = 0x16
        CMD_SUBMIX_GENERATE = 0x17
        CMD_SUBMIX_GENERATE_SIDECHAIN = 0x18
        CMD_SUBMIX_DEBUG = 0x19
        CMD_SUBMIX_MIX2x1 = 0x1A
        CMD_SUBMIX_OUTPUT = 0x1B
        CMD_SUBMIX_OUTPUTx2 = 0x1C
        CMD_SUBMIX_COPY = 0x1D
        CMD_SUBMIX_ACCUMULATE = 0x1E
        CMD_SUBMIX_METER = 0x1F
        CMD_SUBMIX_METER_SPECTRUM = 0x20
        CMD_IMPULSERESPONSE_INPUT_STORE = 0x21
        CMD_PROCESSOR_SET_IMPULSERESPONSE_VALUE = 0x22
        CMD_REMAP_VSND_TO_IMPULSERESPONSE = 0x23
        CMD_IMPULSERESPONSE_RESET = 0x24
        CMD_BLEND_VSNDS_TO_IMPULSERESPONSE = 0x25
        CMD_IMPULSERESPONSE_DELAY = 0x26
    }
    class EWaveform: {
        Sine = 0x0
        Square = 0x1
        Saw = 0x2
        Triangle = 0x3
        Noise = 0x4
    }
    class VMixLFOShape_t: {
        LFO_SHAPE_SINE = 0x0
        LFO_SHAPE_SQUARE = 0x1
        LFO_SHAPE_TRI = 0x2
        LFO_SHAPE_SAW = 0x3
        LFO_SHAPE_NOISE = 0x4
    }
    class VMixFilterType_t: {
        FILTER_UNKNOWN = -1
        FILTER_LOWPASS = 0x0
        FILTER_HIGHPASS = 0x1
        FILTER_BANDPASS = 0x2
        FILTER_NOTCH = 0x3
        FILTER_PEAKING_EQ = 0x4
        FILTER_LOW_SHELF = 0x5
        FILTER_HIGH_SHELF = 0x6
        FILTER_ALLPASS = 0x7
        FILTER_PASSTHROUGH = 0x8
    }
    class SosActionStopType_t: {
        SOS_STOPTYPE_NONE = 0x0
        SOS_STOPTYPE_TIME = 0x1
        SOS_STOPTYPE_OPVAR = 0x2
    }
    class SndSeqTrackPlaybackType_t: {
        eSndSeqTrackPlaybackTypeStep = 0x0
        eSndSeqTrackPlaybackTypeFwd = 0x1
    }
    class SosEditItemType_t: {
        SOS_EDIT_ITEM_TYPE_SOUNDEVENTS = 0x0
        SOS_EDIT_ITEM_TYPE_SOUNDEVENT = 0x1
        SOS_EDIT_ITEM_TYPE_LIBRARYSTACKS = 0x2
        SOS_EDIT_ITEM_TYPE_STACK = 0x3
        SOS_EDIT_ITEM_TYPE_OPERATOR = 0x4
        SOS_EDIT_ITEM_TYPE_FIELD = 0x5
    }
    class SndSeqQuantizeType_t: {
        eSndSeqQuantizeInvalid = -1
        eSndSeqQuantizeNone = 0x0
        eSndSeqQuantizeBeat = 0x1
        eSndSeqQuantizeBar = 0x2
        eSndSeqQuantizeSequence = 0x3
        eSndSeqQuantizeSeek = 0x4
        eSndSeqQuantizeReset = 0x5
    }
    class PlayBackMode_t: {
        Random = 0x0
        RandomNoRepeats = 0x1
        RandomAvoidLast = 0x2
        Sequential = 0x3
        RandomWeights = 0x4
    }
    class SosGroupFieldBehavior_t: {
        kIgnore = 0x0
        kBranch = 0x1
        kMatch = 0x2
    }
    class SndSeqSyncType_t: {
        eSndSeqSyncTypeNone = 0x0
        eSndSeqSyncTypeWait = 0x1
        eSndSeqSyncTypeSeek = 0x2
    }
    class soundlevel_t: {
        SNDLVL_NONE = 0x0
        SNDLVL_20dB = 0x14
        SNDLVL_25dB = 0x19
        SNDLVL_30dB = 0x1E
        SNDLVL_35dB = 0x23
        SNDLVL_40dB = 0x28
        SNDLVL_45dB = 0x2D
        SNDLVL_50dB = 0x32
        SNDLVL_55dB = 0x37
        SNDLVL_IDLE = 0x3C
        SNDLVL_60dB = 0x3C
        SNDLVL_65dB = 0x41
        SNDLVL_STATIC = 0x42
        SNDLVL_70dB = 0x46
        SNDLVL_NORM = 0x4B
        SNDLVL_75dB = 0x4B
        SNDLVL_80dB = 0x50
        SNDLVL_TALKING = 0x50
        SNDLVL_85dB = 0x55
        SNDLVL_90dB = 0x5A
        SNDLVL_95dB = 0x5F
        SNDLVL_100dB = 0x64
        SNDLVL_105dB = 0x69
        SNDLVL_110dB = 0x6E
        SNDLVL_120dB = 0x78
        SNDLVL_130dB = 0x82
        SNDLVL_GUNFIRE = 0x8C
        SNDLVL_140dB = 0x8C
        SNDLVL_150dB = 0x96
        SNDLVL_180dB = 0xB4
    }
    class VMixPannerType_t: {
        PANNER_TYPE_LINEAR = 0x0
        PANNER_TYPE_EQUAL_POWER = 0x1
    }
    class VMixChannelOperation_t: {
        VMIX_CHAN_STEREO = 0x0
        VMIX_CHAN_LEFT = 0x1
        VMIX_CHAN_RIGHT = 0x2
        VMIX_CHAN_SWAP = 0x3
        VMIX_CHAN_MONO = 0x4
        VMIX_CHAN_MID_SIDE = 0x5
    }
    class EMidiNote: {
        C = 0x0
        C_Sharp = 0x1
        D = 0x2
        D_Sharp = 0x3
        E = 0x4
        F = 0x5
        F_Sharp = 0x6
        G = 0x7
        G_Sharp = 0x8
        A = 0x9
        A_Sharp = 0xA
        B = 0xB
        Count = 0xC
    }
    class SndSeqRegionType_t: {
        eSndSeqRegionTypeNull = 0x0
        eSndSeqRegionTypeSndEvt = 0x1
        eSndSeqRegionTypeMidiSeq = 0x2
    }
    class CVSoundFormat_t: {
        PCM16 = 0x0
        PCM8 = 0x1
        MP3 = 0x2
        ADPCM = 0x3
    }
    class VMixFilterSlope_t: {
        FILTER_SLOPE_1POLE_6dB = 0x0
        FILTER_SLOPE_1POLE_12dB = 0x1
        FILTER_SLOPE_1POLE_18dB = 0x2
        FILTER_SLOPE_1POLE_24dB = 0x3
        FILTER_SLOPE_12dB = 0x4
        FILTER_SLOPE_24dB = 0x5
        FILTER_SLOPE_36dB = 0x6
        FILTER_SLOPE_48dB = 0x7
        FILTER_SLOPE_MAX = 0x7
    }
    class SndSeqPlayerType_t: {
        eSndSeqPlayerNull = 0x0
        eSndSeqPlayerSndEvt = 0x1
        eSndSeqPlayerMidiSeq = 0x2
    }
    class SosActionLimitSortType_t: {
        SOS_LIMIT_SORTTYPE_HIGHEST = 0x0
        SOS_LIMIT_SORTTYPE_LOWEST = 0x1
    }
    class VMixSubgraphSwitchInterpolationType_t: {
        SUBGRAPH_INTERPOLATION_TEMPORAL_CROSSFADE = 0x0
        SUBGRAPH_INTERPOLATION_TEMPORAL_FADE_OUT = 0x1
        SUBGRAPH_INTERPOLATION_KEEP_LAST_SUBGRAPH_RUNNING = 0x2
    }
    class SosGroupType_t: {
        SOS_GROUPTYPE_DYNAMIC = 0x0
        SOS_GROUPTYPE_STATIC = 0x1
    }
    class SosActionSetParamSortType_t: {
        SOS_SETPARAM_SORTTYPE_HIGHEST = 0x0
        SOS_SETPARAM_SORTTYPE_LOWEST = 0x1
    }
    class SndSeqMidiStatusType_t: {
        SndSeqMidiStatusNoteOff = 0x8
        SndSeqMidiStatusNoteOn = 0x9
        SndSeqMidiStatusKeyPressure = 0xA
        SndSeqMidiStatusCtrlChange = 0xB
        SndSeqMidiStatusProgramChange = 0xC
        SndSeqMidiStatusChannelPressure = 0xD
        SndSeqMidiStatusPitchBend = 0xE
    }
    class CVMixInputBase: {
         = 0x0 # 
    }
    class CVoiceContainerBlender: {
        pass
    }
    class CVMixPitchShiftProcessorDesc: {
        pass
    }
    class VMixFreeverbDesc_t: {
         = 0x0 # 
    }
    class CVoiceContainerStaticAdditiveSynth__CHarmonic: {
         = 0x0 # 
    }
    class CVoiceContainerStaticAdditiveSynth__CTone: {
         = 0x0 # 
    }
    class CSosGroupActionOcclusionSchema: {
        pass
    }
    class CVoiceContainerRandomSampler: {
        pass
    }
    class CVMixSteamAudioDirectProcessorDesc: {
        pass
    }
    class CVMixSteamAudioHRTFProcessorDesc: {
        pass
    }
    class CVoiceContainerDefault: {
        pass
    }
    class CVSound: {
         = 0x0 # 
    }
    class CDSPPresetMixgroupModifierTable: {
         = 0x0 # 
    }
    class CSosGroupActionSoundeventClusterSchema: {
        pass
    }
    class CSosGroupActionSetSoundeventParameterSchema: {
        pass
    }
    class CSoundContainerReference: {
         = 0x0 # 
    }
    class CVoiceContainerNull: {
        pass
    }
    class VMixSubgraphSwitchDesc_t: {
         = 0x0 # 
    }
    class CVoiceContainerAnalysisBase: {
         = 0x0 # 
    }
    class CSosGroupActionSoundeventMinMaxValuesSchema: {
        pass
    }
    class CVMixEnvelopeProcessorDesc: {
        pass
    }
    class CVMixCommand: {
         = 0x0 # 
    }
    class SamplerVoice_t: {
        pass
    }
    class CVMixControlInput: {
        pass
    }
    class CVMixBoxverbProcessorDesc: {
        pass
    }
    class CVMixDynamicsCompressorProcessorDesc: {
        pass
    }
    class VMixPannerDesc_t: {
         = 0x0 # 
    }
    class CSosGroupActionSoundeventPrioritySchema: {
        pass
    }
    class CVoiceContainerRealtimeFMSineWave: {
        pass
    }
    class SelectedEditItemInfo_t: {
         = 0x0 # 
    }
    class VMixModDelayDesc_t: {
         = 0x0 # 
    }
    class CSndSeqInstSndEvtSchema: {
        pass
    }
    class CVMixNameInputMeter: {
        pass
    }
    class CSndSeqInstruments: {
        pass
    }
    class CVMixDynamics3BandProcessorDesc: {
        pass
    }
    class VMixBoxverbDesc_t: {
         = 0x0 # 
    }
    class CSosGroupActionSchema: {
        pass
    }
    class CSosSoundEventGroupSchema: {
         = 0x0 # 
    }
    class CSndSeqInstMidiSampler: {
        pass
    }
    class CSndSeqInstBaseSchema: {
        pass
    }
    class VMixDynamics3BandDesc_t: {
         = 0x0 # 
    }
    class CVMixEQ8ProcessorDesc: {
        pass
    }
    class CDSPMixgroupModifier: {
         = 0x0 # 
    }
    class CAudioMorphData: {
         = 0x0 # 
    }
    class VMixDualCompressorDesc_t: {
         = 0x0 # 
    }
    class CVoiceContainerStaticAdditiveSynth: {
        pass
    }
    class CVoiceContainerShapedNoise: {
        pass
    }
    class CDspPresetModifierList: {
         = 0x0 # 
    }
    class CVoiceContainerBase: {
        pass
    }
    class CVMixDiffusorProcessorDesc: {
        pass
    }
    class CVMixUtilityProcessorDesc: {
        pass
    }
    class CVoiceContainerGranulator: {
        pass
    }
    class CVMixPresetDSPProcessorDesc: {
        pass
    }
    class VMixDelayDesc_t: {
         = 0x0 # 
    }
    class VMixEQ8Desc_t: {
         = 0x0 # 
    }
    class CVMixDynamicsProcessorDesc: {
        pass
    }
    class CVMixGraphDescData: {
         = 0x0 # 
    }
    class CVoiceContainerLoopXFade: {
        pass
    }
    class VMixPresetDSPDesc_t: {
         = 0x0 # 
    }
    class CAudioPhonemeTag: {
         = 0x0 # 
    }
    class CVMixControlInputArray: {
        pass
    }
    class CVMixNameInput: {
        pass
    }
    class CSosGroupActionSoundeventCountSchema: {
        pass
    }
    class CVoiceContainerEnvelopeAnalyzer: {
        pass
    }
    class CVMixBaseProcessorDesc: {
        pass
    }
    class CVMixImpulseResponseInput: {
        pass
    }
    class CVMixSteamAudioHybridReverbProcessorDesc: {
        pass
    }
    class CSoundEventMetaData: {
         = 0x0 # 
    }
    class VMixPitchShiftDesc_t: {
         = 0x0 # 
    }
    class CVMixControlOutput: {
        pass
    }
    class CVMixModDelayProcessorDesc: {
        pass
    }
    class CVMixShaperProcessorDesc: {
        pass
    }
    class CVMixAutomaticControlInput: {
         = 0x0 # 
    }
    class CAudioEmphasisSample: {
         = 0x0 # 
    }
    class CVMixOscProcessorDesc: {
        pass
    }
    class CVMixCurveHeader: {
         = 0x0 # 
    }
    class CVoiceContainerGenerator: {
        pass
    }
    class CVoiceContainerSet: {
        pass
    }
    class VMixConvolutionDesc_t: {
         = 0x0 # 
    }
    class CVoiceContainerSetElement: {
         = 0x0 # 
    }
    class CVoiceContainerAsyncGenerator: {
        pass
    }
    class CSoundInfoHeader: {
        pass
    }
    class SosEditItemInfo_t: {
         = 0x0 # 
    }
    class CVMixFlangerProcessorDesc: {
        pass
    }
    class CVMixEffectChainProcessorDesc: {
        pass
    }
    class KeyGroup_t: {
        pass
    }
    class CVMixFreeverbProcessorDesc: {
        pass
    }
    class VMixPlateverbDesc_t: {
         = 0x0 # 
    }
    class CVMixConvolutionProcessorDesc: {
        pass
    }
    class CSoundContainerReferenceArray: {
         = 0x0 # 
    }
    class CVMixFilterProcessorDesc: {
        pass
    }
    class CVMixAdditionalOutput: {
         = 0x0 # 
    }
    class CVoiceContainerTapePlayer: {
        pass
    }
    class CVMixSubgraphSwitchProcessorDesc: {
        pass
    }
    class VMixDiffusorDesc_t: {
         = 0x0 # 
    }
    class CVMixSteamAudioPathingProcessorDesc: {
        pass
    }
    class CVMixPannerProcessorDesc: {
        pass
    }
    class VMixDynamicsCompressorDesc_t: {
         = 0x0 # 
    }
    class CVMixStereoDelayProcessorDesc: {
        pass
    }
    class VMixShaperDesc_t: {
         = 0x0 # 
    }
    class VMixEnvelopeDesc_t: {
         = 0x0 # 
    }
    class CAudioSentence: {
         = 0x0 # 
    }
    class CVoiceContainerParameterBlender: {
        pass
    }
    class CVMixAudioMeter: {
         = 0x0 # 
    }
    class CVMixVocoderProcessorDesc: {
        pass
    }
    class CSosGroupActionLimitSchema: {
        pass
    }
    class CVoiceContainerAmpedDecayingSineWave: {
        pass
    }
    class CVoiceContainerEnvelope: {
        pass
    }
    class VMixAutoFilterDesc_t: {
         = 0x0 # 
    }
    class VMixDynamicsBand_t: {
         = 0x0 # 
    }
    class VMixEffectChainDesc_t: {
         = 0x0 # 
    }
    class CVMixPlateReverbProcessorDesc: {
        pass
    }
    class CVoiceContainerMultiBlender: {
        pass
    }
    class CVMixVsndInput: {
        pass
    }
    class CVoiceContainerStaticAdditiveSynth__CGainScalePerInstance: {
         = 0x0 # 
    }
    class VelocityZone_t: {
        pass
    }
    class CVoiceContainerSelector: {
        pass
    }
    class CSosGroupActionTimeBlockLimitSchema: {
        pass
    }
    class CSosGroupActionMemberCountEnvelopeSchema: {
        pass
    }
    class CVMixDualCompressorProcessorDesc: {
        pass
    }
    class CVoiceContainerSwitch: {
        pass
    }
    class CVMixControlMeter: {
        pass
    }
    class CVoiceContainerEnum: {
        pass
    }
    class CSosGroupActionTimeLimitSchema: {
        pass
    }
    class VMixVocoderDesc_t: {
         = 0x0 # 
    }
    class VMixUtilityDesc_t: {
         = 0x0 # 
    }
    class CVoiceContainerLoopTrigger: {
        pass
    }
    class CVoiceContainerDecayingSineWave: {
        pass
    }
    class CVMixDelayProcessorDesc: {
        pass
    }
    class CVMixBoxverb2ProcessorDesc: {
        pass
    }
    class VMixFilterDesc_t: {
         = 0x0 # 
    }
    class VMixOscDesc_t: {
         = 0x0 # 
    }
    class CVMixAutoFilterProcessorDesc: {
        pass
    }
    class ISndSeqInstruments: {
        pass
    }
    class VMixFlangerDesc_t: {
         = 0x0 # 
    }
    class VMixDynamicsDesc_t: {
         = 0x0 # 
    }
}
