#   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
#   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
#   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
#   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
#   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
#   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
# 
# Generated by ExitScam Dumper
# 
# Timestamp: 2026-04-21T00:48:31.099236600+00:00
# Build No: 14151
# Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
#

# Module: steamaudio.dll
class SteamaudioDll: {
    class SteamAudioReverbClusteringSettings_t: {
         = 0x0 # 
    }
    class SteamAudioCustomDataDimensionsSettings_t: {
         = 0x0 # 
    }
    class SteamAudioPathSettings_t: {
         = 0x0 # 
    }
    class CSteamAudioAmbisonicsField: {
         = 0x0 # 
    }
    class CSteamAudioBakedPathingData: {
         = 0x0 # 
    }
    class SteamAudioReverbSettings_t: {
         = 0x0 # 
    }
    class CSteamAudioProbeData: {
         = 0x0 # 
    }
    class SteamAudioReverbCompressionSettings_t: {
         = 0x0 # 
    }
    class CSteamAudioBakedMaterialsData: {
         = 0x0 # 
    }
    class CSteamAudioBakedOcclusionData: {
         = 0x0 # 
    }
    class CSteamAudioBakedReverbData: {
         = 0x0 # 
    }
    class CSteamAudioProbeLineSegment: {
         = 0x0 # 
    }
    class SteamAudioCustomDataOcclusionSettings_t: {
         = 0x0 # 
    }
    class CSteamAudioBakedDimensionsData: {
         = 0x0 # 
    }
    class CSteamAudioSceneData: {
         = 0x0 # 
    }
    class CSteamAudioProbeGrid: {
         = 0x0 # 
    }
    class CSteamAudioCompressedReverb: {
         = 0x0 # 
    }
}
