//   ███████╗██╗  ██╗██╗████████╗███████╗ ██████╗ █████╗ ███╗   ███╗
//   ██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗████╗ ████║
//   █████╗   ╚███╔╝ ██║   ██║   ███████╗██║     ███████║██╔████╔██║
//   ██╔══╝   ██╔██╗ ██║   ██║   ╚════██║██║     ██╔══██║██║╚██╔╝██║
//   ███████╗██╔╝ ██╗██║   ██║   ███████║╚██████╗██║  ██║██║ ╚═╝ ██║
//   ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝
// 
// Generated by ExitScam Dumper
// 
// Timestamp: 2026-04-21T00:48:31.099236600+00:00
// Build No: 14151
// Classes: 3222 | Enums: 480 | Offsets: 31 | Modules: 18
//

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, unused)]

pub mod exitscam {
    pub mod schemas {
        // Module: steamaudio.dll
        // Class count: 17
        // Enum count: 0
        pub mod steamaudio_dll {
            // Parent: None
            // Field count: 1
            pub mod SteamAudioReverbClusteringSettings_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod SteamAudioCustomDataDimensionsSettings_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod SteamAudioPathSettings_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioAmbisonicsField {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioBakedPathingData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod SteamAudioReverbSettings_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioProbeData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod SteamAudioReverbCompressionSettings_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioBakedMaterialsData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioBakedOcclusionData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioBakedReverbData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioProbeLineSegment {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod SteamAudioCustomDataOcclusionSettings_t {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioBakedDimensionsData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioSceneData {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioProbeGrid {
                pub const : usize = 0x0; // 
            }
            // Parent: None
            // Field count: 1
            pub mod CSteamAudioCompressedReverb {
                pub const : usize = 0x0; // 
            }
        }
    }
}
